services:
  backend:
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 4

  backup:
    image: postgres:15
    depends_on:
      - db
    volumes:
      - ./backups:/backups
    env_file:
      - .env
    entrypoint: >
      sh -c 'while true; do
               pg_dump -h db -U $POSTGRES_USER -F c -f /backups/db_backup_$(date +%Y%m%d).dump;
               sleep 86400;
             done'

