"""add_triggered_buffs_to_free_training_record_table

Revision ID: 04f23c05a42a
Revises: ee2273c09478
Create Date: 2026-05-14 07:39:22.058527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04f23c05a42a'
down_revision: Union[str, None] = 'ee2273c09478'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bike_free_training_records', sa.Column('triggered_buffs', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('running_free_training_records', sa.Column('triggered_buffs', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
