"""add created_at field in cpasset & equipcard table

Revision ID: 0e304109392b
Revises: 1e3bb96e83be
Create Date: 2025-12-09 03:15:41.663741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e304109392b'
down_revision: Union[str, None] = '1e3bb96e83be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_cpassets', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('user_equipment_cards', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_equipment_cards', 'created_at')
    op.drop_column('user_cpassets', 'created_at')
    # ### end Alembic commands ###
