"""add bonus_ratio to card_bonus table

Revision ID: 0fddd560bf0e
Revises: bcf518f08ce3
Create Date: 2025-11-18 07:27:21.040644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fddd560bf0e'
down_revision: Union[str, None] = 'bcf518f08ce3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bike_bonus_by_team_members', sa.Column('is_applied', sa.Boolean(), nullable=False))
    op.drop_column('bike_bonus_by_team_members', 'is_valid')
    op.add_column('card_bonus_in_bike_records', sa.Column('bonus_ratio', sa.Float(), nullable=True))
    op.add_column('card_bonus_in_running_records', sa.Column('bonus_ratio', sa.Float(), nullable=True))
    op.add_column('running_bonus_by_team_members', sa.Column('is_applied', sa.Boolean(), nullable=False))
    op.drop_column('running_bonus_by_team_members', 'is_valid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('running_bonus_by_team_members', sa.Column('is_valid', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('running_bonus_by_team_members', 'is_applied')
    op.drop_column('card_bonus_in_running_records', 'bonus_ratio')
    op.drop_column('card_bonus_in_bike_records', 'bonus_ratio')
    op.add_column('bike_bonus_by_team_members', sa.Column('is_valid', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('bike_bonus_by_team_members', 'is_applied')
    # ### end Alembic commands ###
