"""change report to REPORT in enum feedbacktype

Revision ID: 11f7da61232f
Revises: faadb4921b95
Create Date: 2025-12-11 23:29:07.812772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11f7da61232f'
down_revision: Union[str, None] = 'faadb4921b95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE feedbackmailtype RENAME VALUE 'report' TO 'REPORT';")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
