"""add daily_task & task_record table

Revision ID: 13b4bab9d4f3
Revises: 3274263267b1
Create Date: 2025-10-24 00:55:06.941961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '13b4bab9d4f3'
down_revision: Union[str, None] = '3274263267b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    dailytasktype_enum = postgresql.ENUM('distance', 'time', name='dailytasktype')
    dailytasktype_enum.create(op.get_bind(), checkfirst=True)

    op.create_table('bike_daily_task',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', postgresql.ENUM('distance', 'time', name='dailytasktype', create_type=False), nullable=False),
    sa.Column('total_progress', sa.Float(), nullable=False),
    sa.Column('reward_stage1', sa.Integer(), nullable=True),
    sa.Column('reward_stage2', sa.Integer(), nullable=True),
    sa.Column('reward_stage3', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bike_daily_task_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', postgresql.ENUM('distance', 'time', name='dailytasktype', create_type=False), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'type', 'date', name='uq_bike_daily_task_user_type_date')
    )
    op.create_index(op.f('ix_bike_daily_task_records_user_id'), 'bike_daily_task_records', ['user_id'], unique=False)
    op.create_table('running_daily_task',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', postgresql.ENUM('distance', 'time', name='dailytasktype', create_type=False), nullable=False),
    sa.Column('total_progress', sa.Float(), nullable=False),
    sa.Column('reward_stage1', sa.Integer(), nullable=True),
    sa.Column('reward_stage2', sa.Integer(), nullable=True),
    sa.Column('reward_stage3', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('running_daily_task_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', postgresql.ENUM('distance', 'time', name='dailytasktype', create_type=False), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'type', 'date', name='uq_running_daily_task_user_type_date')
    )
    op.create_index(op.f('ix_running_daily_task_records_user_id'), 'running_daily_task_records', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_running_daily_task_records_user_id'), table_name='running_daily_task_records')
    op.drop_table('running_daily_task_records')
    op.drop_table('running_daily_task')
    op.drop_index(op.f('ix_bike_daily_task_records_user_id'), table_name='bike_daily_task_records')
    op.drop_table('bike_daily_task_records')
    op.drop_table('bike_daily_task')
    # ### end Alembic commands ###
