"""add is_on_shelves property in cpasset_price table

Revision ID: 13d0242e713f
Revises: 8a76009cd2ce
Create Date: 2025-07-02 08:21:45.299572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13d0242e713f'
down_revision: Union[str, None] = '8a76009cd2ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cpasset_price', sa.Column('is_on_shelves', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cpasset_price', 'is_on_shelves')
    # ### end Alembic commands ###
