"""change status from str to enum in bike_teams table

Revision ID: 152275672bab
Revises: 765212041c90
Create Date: 2025-06-30 21:13:30.866851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '152275672bab'
down_revision: Union[str, None] = '765212041c90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    teamstatus_enum = postgresql.ENUM('prepared', 'ready', 'recording', name='teamstatus')
    teamstatus_enum.create(op.get_bind(), checkfirst=True)
    op.alter_column('bike_teams', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('prepared', 'ready', 'recording', name='teamstatus'),
               existing_nullable=True, postgresql_using="status::teamstatus")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bike_teams', 'status',
               existing_type=sa.Enum('prepared', 'ready', 'recording', name='teamstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
