"""baseline schema

Revision ID: 15558fadf600
Revises: 750c5dc73b19
Create Date: 2026-01-28 22:01:26.057744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = '15558fadf600'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")

    op.create_table('announcements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('banner_ads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ad_id', sa.String(), nullable=False),
    sa.Column('image_url_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('web_url', sa.String(), nullable=True),
    sa.Column('is_displayed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_banner_ads_ad_id'), 'banner_ads', ['ad_id'], unique=True)
    op.create_table('bike_bonus_by_team_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('bonus_in_ratio', sa.Float(), nullable=True),
    sa.Column('bonus_in_seconds', sa.Float(), nullable=True),
    sa.Column('is_applied', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'team_id', name='uq_bike_bonus_by_team_members_user_team')
    )
    op.create_index(op.f('ix_bike_bonus_by_team_members_team_id'), 'bike_bonus_by_team_members', ['team_id'], unique=False)
    op.create_index(op.f('ix_bike_bonus_by_team_members_user_id'), 'bike_bonus_by_team_members', ['user_id'], unique=False)
    op.create_table('bike_career_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('season_id', sa.UUID(), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', name='gender'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('voucher_bonus', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id', 'user_id', name='uq_bike_career_score_season_user')
    )
    op.create_index(op.f('ix_bike_career_scores_season_id'), 'bike_career_scores', ['season_id'], unique=False)
    op.create_index(op.f('ix_bike_career_scores_user_id'), 'bike_career_scores', ['user_id'], unique=False)
    op.create_table('bike_career_statistic_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('season_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('total_distance', sa.Float(), nullable=False),
    sa.Column('total_time', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id', 'user_id', name='uq_bike_career_statistic_season_user')
    )
    op.create_index(op.f('ix_bike_career_statistic_data_season_id'), 'bike_career_statistic_data', ['season_id'], unique=False)
    op.create_index(op.f('ix_bike_career_statistic_data_user_id'), 'bike_career_statistic_data', ['user_id'], unique=False)
    op.create_table('bike_daily_task',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('distance', 'time', name='dailytasktype'), nullable=False),
    sa.Column('total_progress', sa.Float(), nullable=False),
    sa.Column('reward_stage1_type', sa.Enum('COIN', 'COUPON', 'VOUCHER', 'STONE1', 'STONE2', 'STONE3', name='ccassettype'), nullable=False),
    sa.Column('reward_stage1', sa.Integer(), nullable=False),
    sa.Column('reward_stage2_type', sa.Enum('COIN', 'COUPON', 'VOUCHER', 'STONE1', 'STONE2', 'STONE3', name='ccassettype'), nullable=False),
    sa.Column('reward_stage2', sa.Integer(), nullable=False),
    sa.Column('reward_stage3_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bike_daily_task_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('distance', 'time', name='dailytasktype'), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('is_reward1_received', sa.Boolean(), nullable=False),
    sa.Column('is_reward2_received', sa.Boolean(), nullable=False),
    sa.Column('is_reward3_received', sa.Boolean(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'type', 'date', name='uq_bike_daily_task_user_type_date')
    )
    op.create_index(op.f('ix_bike_daily_task_records_user_id'), 'bike_daily_task_records', ['user_id'], unique=False)
    op.create_table('bike_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('name_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('region_id', sa.UUID(), nullable=False),
    sa.Column('season_id', sa.UUID(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bike_events_event_id'), 'bike_events', ['event_id'], unique=True)
    op.create_table('bike_leaderboard',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('track_id', sa.UUID(), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', name='gender'), nullable=False),
    sa.Column('rank_position', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('reward', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('track_id', 'user_id', name='uq_bike_leaderboard_track_user')
    )
    op.create_index(op.f('ix_bike_leaderboard_record_id'), 'bike_leaderboard', ['record_id'], unique=False)
    op.create_index(op.f('ix_bike_leaderboard_track_id'), 'bike_leaderboard', ['track_id'], unique=False)
    op.create_index(op.f('ix_bike_leaderboard_user_id'), 'bike_leaderboard', ['user_id'], unique=False)
    op.create_table('bike_race_paths',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('path_id', sa.String(), nullable=False),
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('path', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bike_race_paths_path_id'), 'bike_race_paths', ['path_id'], unique=True)
    op.create_table('bike_race_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('record_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('track_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('path_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('notStarted', 'recording', 'completed', 'expired', 'toBeVerified', 'invalid', name='recordstatus'), nullable=False),
    sa.Column('validation_score', sa.Float(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('is_finish_bonus_computing', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bike_race_records_record_id'), 'bike_race_records', ['record_id'], unique=True)
    op.create_table('bike_seasons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('season_id', sa.String(), nullable=False),
    sa.Column('name_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bike_seasons_season_id'), 'bike_seasons', ['season_id'], unique=True)
    op.create_table('bike_team_applied_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.String(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('introduction', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bike_team_applied_members_member_id'), 'bike_team_applied_members', ['member_id'], unique=True)
    op.create_table('bike_team_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.String(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('is_leader', sa.Boolean(), nullable=False),
    sa.Column('is_registered', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bike_team_members_member_id'), 'bike_team_members', ['member_id'], unique=True)
    op.create_table('bike_teams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('team_code', sa.String(), nullable=False),
    sa.Column('track_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('members_count_max', sa.Integer(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('prepared', 'locked', 'ready', 'recording', 'completed', name='teamstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('start_date_real', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bike_teams_team_id'), 'bike_teams', ['team_id'], unique=True)
    op.create_index('uq_bike_teams_teamcode_status', 'bike_teams', ['team_code'], unique=True, postgresql_where=sa.text("status IN ('prepared', 'locked', 'ready', 'recording')"))
    op.create_table('bike_tracks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('track_id', sa.String(), nullable=False),
    sa.Column('name_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('from_lat', sa.Float(), nullable=False),
    sa.Column('from_lng', sa.Float(), nullable=False),
    sa.Column('from_radius', sa.Integer(), nullable=False),
    sa.Column('to_lat', sa.Float(), nullable=False),
    sa.Column('to_lng', sa.Float(), nullable=False),
    sa.Column('to_radius', sa.Integer(), nullable=False),
    sa.Column('single_register_card_id', sa.UUID(), nullable=False),
    sa.Column('team_register_card_id', sa.UUID(), nullable=False),
    sa.Column('elevation_difference', sa.Integer(), nullable=False),
    sa.Column('sub_region_name_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prize_pool', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('distance', sa.Float(), nullable=False),
    sa.Column('terrain_type', sa.Enum('road', 'crossCountry', 'enduro', 'downHill', 'other', name='biketrackterraintype'), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bike_tracks_track_id'), 'bike_tracks', ['track_id'], unique=True)
    op.create_table('card_bonus_in_bike_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('bonus_ratio', sa.Float(), nullable=True),
    sa.Column('bonus_time', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('card_bonus_in_running_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('bonus_ratio', sa.Float(), nullable=True),
    sa.Column('bonus_time', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ccasset_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('asset_type', sa.Enum('COIN', 'COUPON', 'VOUCHER', 'STONE1', 'STONE2', 'STONE3', name='ccassettype'), nullable=False),
    sa.Column('operation', sa.Enum('RECHARGE', 'CONSUME', 'TRANSFER', 'REWARD', 'WITHDRAW', 'REFUND', 'DESTROY', 'UPGRADE', name='assetoperation'), nullable=False),
    sa.Column('change_amount', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coupon_prices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('gift_price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_table('coupon_recharge_transaction',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('original_transaction_id', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('app_account_token', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cp_asset_defs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('prop_type', sa.Enum('registration_card', 'team_card', name='cpassettype'), nullable=False),
    sa.Column('name_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cp_asset_defs_asset_id'), 'cp_asset_defs', ['asset_id'], unique=True)
    op.create_table('cpasset_price',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prop_def_id', sa.UUID(), nullable=False),
    sa.Column('ccasset_type', sa.Enum('COIN', 'COUPON', 'VOUCHER', 'STONE1', 'STONE2', 'STONE3', name='ccassettype'), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('is_on_shelves', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prop_def_id', name='uix_cpasset_price_prop_def_id')
    )
    op.create_table('cpasset_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('prop_def_id', sa.UUID(), nullable=False),
    sa.Column('operation', sa.Enum('RECHARGE', 'CONSUME', 'TRANSFER', 'REWARD', 'WITHDRAW', 'REFUND', 'DESTROY', 'UPGRADE', name='assetoperation'), nullable=False),
    sa.Column('change_amount', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_device_id'), 'devices', ['device_id'], unique=True)
    op.create_table('equip_card_price',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('def_id', sa.UUID(), nullable=False),
    sa.Column('ccasset_type', sa.Enum('COIN', 'COUPON', 'VOUCHER', 'STONE1', 'STONE2', 'STONE3', name='ccassettype'), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('is_on_shelves', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('def_id', name='uix_equip_card_price_def_id')
    )
    op.create_table('equip_card_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('card_def_id', sa.UUID(), nullable=False),
    sa.Column('operation', sa.Enum('RECHARGE', 'CONSUME', 'TRANSFER', 'REWARD', 'WITHDRAW', 'REFUND', 'DESTROY', 'UPGRADE', name='assetoperation'), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment_card_defs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('def_id', sa.String(), nullable=False),
    sa.Column('name_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sport_type', sa.Enum('running', 'bike', name='sporttype'), nullable=False),
    sa.Column('rarity', sa.String(), nullable=False),
    sa.Column('description_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('skill1_description_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('skill2_description_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('skill3_description_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('effect_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_card_defs_def_id'), 'equipment_card_defs', ['def_id'], unique=True)
    op.create_table('feedback_mailbox',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mail_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('user_contact_info', sa.String(), nullable=True),
    sa.Column('mail_type', sa.Enum('IAP', 'BUG', 'FEATURE', 'REPORT', 'OTHER', name='feedbackmailtype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_handled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_mailbox_mail_id'), 'feedback_mailbox', ['mail_id'], unique=True)
    op.create_index(op.f('ix_feedback_mailbox_user_id'), 'feedback_mailbox', ['user_id'], unique=False)
    op.create_table('mailbox',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mail_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('mail_type', sa.Enum('REWARD', 'NOTIFICATION', name='mailtype'), nullable=False),
    sa.Column('title_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('attachment', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_received', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mailbox_mail_id'), 'mailbox', ['mail_id'], unique=True)
    op.create_index(op.f('ix_mailbox_user_id'), 'mailbox', ['user_id'], unique=False)
    op.create_table('regions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('region_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country_code', sa.String(), nullable=False),
    sa.Column('boundary', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    #op.create_index('idx_regions_boundary', 'regions', ['boundary'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_regions_region_id'), 'regions', ['region_id'], unique=True)
    op.create_table('running_bonus_by_team_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('bonus_in_ratio', sa.Float(), nullable=True),
    sa.Column('bonus_in_seconds', sa.Float(), nullable=True),
    sa.Column('is_applied', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'team_id', name='uq_running_bonus_by_team_members_user_team')
    )
    op.create_index(op.f('ix_running_bonus_by_team_members_team_id'), 'running_bonus_by_team_members', ['team_id'], unique=False)
    op.create_index(op.f('ix_running_bonus_by_team_members_user_id'), 'running_bonus_by_team_members', ['user_id'], unique=False)
    op.create_table('running_career_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('season_id', sa.UUID(), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', name='gender'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('voucher_bonus', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id', 'user_id', name='uq_running_career_score_season_user')
    )
    op.create_index(op.f('ix_running_career_scores_season_id'), 'running_career_scores', ['season_id'], unique=False)
    op.create_index(op.f('ix_running_career_scores_user_id'), 'running_career_scores', ['user_id'], unique=False)
    op.create_table('running_career_statistic_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('season_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('total_distance', sa.Float(), nullable=False),
    sa.Column('total_time', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id', 'user_id', name='uq_running_career_statistic_season_user')
    )
    op.create_index(op.f('ix_running_career_statistic_data_season_id'), 'running_career_statistic_data', ['season_id'], unique=False)
    op.create_index(op.f('ix_running_career_statistic_data_user_id'), 'running_career_statistic_data', ['user_id'], unique=False)
    op.create_table('running_daily_task',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('distance', 'time', name='dailytasktype'), nullable=False),
    sa.Column('total_progress', sa.Float(), nullable=False),
    sa.Column('reward_stage1_type', sa.Enum('COIN', 'COUPON', 'VOUCHER', 'STONE1', 'STONE2', 'STONE3', name='ccassettype'), nullable=False),
    sa.Column('reward_stage1', sa.Integer(), nullable=False),
    sa.Column('reward_stage2_type', sa.Enum('COIN', 'COUPON', 'VOUCHER', 'STONE1', 'STONE2', 'STONE3', name='ccassettype'), nullable=False),
    sa.Column('reward_stage2', sa.Integer(), nullable=False),
    sa.Column('reward_stage3_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('running_daily_task_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('distance', 'time', name='dailytasktype'), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('is_reward1_received', sa.Boolean(), nullable=False),
    sa.Column('is_reward2_received', sa.Boolean(), nullable=False),
    sa.Column('is_reward3_received', sa.Boolean(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'type', 'date', name='uq_running_daily_task_user_type_date')
    )
    op.create_index(op.f('ix_running_daily_task_records_user_id'), 'running_daily_task_records', ['user_id'], unique=False)
    op.create_table('running_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('name_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('region_id', sa.UUID(), nullable=False),
    sa.Column('season_id', sa.UUID(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_running_events_event_id'), 'running_events', ['event_id'], unique=True)
    op.create_table('running_leaderboard',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('track_id', sa.UUID(), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', name='gender'), nullable=False),
    sa.Column('rank_position', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('reward', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('track_id', 'user_id', name='uq_running_leaderboard_track_user')
    )
    op.create_index(op.f('ix_running_leaderboard_record_id'), 'running_leaderboard', ['record_id'], unique=False)
    op.create_index(op.f('ix_running_leaderboard_track_id'), 'running_leaderboard', ['track_id'], unique=False)
    op.create_index(op.f('ix_running_leaderboard_user_id'), 'running_leaderboard', ['user_id'], unique=False)
    op.create_table('running_race_paths',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('path_id', sa.String(), nullable=False),
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('path', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_running_race_paths_path_id'), 'running_race_paths', ['path_id'], unique=True)
    op.create_table('running_race_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('record_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('track_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('path_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('notStarted', 'recording', 'completed', 'expired', 'toBeVerified', 'invalid', name='recordstatus'), nullable=False),
    sa.Column('validation_score', sa.Float(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('is_finish_bonus_computing', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_running_race_records_record_id'), 'running_race_records', ['record_id'], unique=True)
    op.create_table('running_seasons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('season_id', sa.String(), nullable=False),
    sa.Column('name_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_running_seasons_season_id'), 'running_seasons', ['season_id'], unique=True)
    op.create_table('running_team_applied_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.String(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('introduction', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_running_team_applied_members_member_id'), 'running_team_applied_members', ['member_id'], unique=True)
    op.create_table('running_team_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.String(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('is_leader', sa.Boolean(), nullable=False),
    sa.Column('is_registered', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_running_team_members_member_id'), 'running_team_members', ['member_id'], unique=True)
    op.create_table('running_teams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('team_code', sa.String(), nullable=False),
    sa.Column('track_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('members_count_max', sa.Integer(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('prepared', 'locked', 'ready', 'recording', 'completed', name='teamstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('start_date_real', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_running_teams_team_id'), 'running_teams', ['team_id'], unique=True)
    op.create_index('uq_running_teams_teamcode_status', 'running_teams', ['team_code'], unique=True, postgresql_where=sa.text("status IN ('prepared', 'locked', 'ready', 'recording')"))
    op.create_table('running_tracks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('track_id', sa.String(), nullable=False),
    sa.Column('name_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('from_lat', sa.Float(), nullable=False),
    sa.Column('from_lng', sa.Float(), nullable=False),
    sa.Column('from_radius', sa.Integer(), nullable=False),
    sa.Column('to_lat', sa.Float(), nullable=False),
    sa.Column('to_lng', sa.Float(), nullable=False),
    sa.Column('to_radius', sa.Integer(), nullable=False),
    sa.Column('single_register_card_id', sa.UUID(), nullable=False),
    sa.Column('team_register_card_id', sa.UUID(), nullable=False),
    sa.Column('elevation_difference', sa.Integer(), nullable=False),
    sa.Column('sub_region_name_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prize_pool', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('distance', sa.Float(), nullable=False),
    sa.Column('terrain_type', sa.Enum('road', 'mountain', name='runningtrackterraintype'), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_running_tracks_track_id'), 'running_tracks', ['track_id'], unique=True)
    op.create_table('sign_in_rewards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('reward_type', sa.Enum('COIN', 'COUPON', 'VOUCHER', 'STONE1', 'STONE2', 'STONE3', name='ccassettype'), nullable=False),
    sa.Column('reward_count', sa.Integer(), nullable=False),
    sa.Column('reward_type_vip', sa.Enum('COIN', 'COUPON', 'VOUCHER', 'STONE1', 'STONE2', 'STONE3', name='ccassettype'), nullable=False),
    sa.Column('reward_count_vip', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscription_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('rewarded', 'created', 'renewed', 'refunded', 'auto_renew_off', 'auto_renew_on', 'grace_started', 'grace_ended', name='subscriptioneventtype'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_events_subscription_id'), 'subscription_events', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_subscription_events_user_id'), 'subscription_events', ['user_id'], unique=False)
    op.create_table('subscription_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('period', sa.Enum('monthly', 'quarterly', 'yearly', name='subscriptionperiod'), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('apple_product_id', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('apple_product_id'),
    sa.UniqueConstraint('plan_code')
    )
    op.create_table('test_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user_bans_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('banned_times', sa.Integer(), nullable=False),
    sa.Column('unban_time', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_ccassets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('asset_type', sa.Enum('COIN', 'COUPON', 'VOUCHER', 'STONE1', 'STONE2', 'STONE3', name='ccassettype'), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('can_recharge', sa.Boolean(), nullable=False),
    sa.Column('can_withdraw', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'asset_type', name='uix_user_ccasset')
    )
    op.create_table('user_cpassets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('prop_def_id', sa.UUID(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'prop_def_id', name='uix_user_cpasset')
    )
    op.create_table('user_equipment_cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('equipment_def_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('skill1_level', sa.Integer(), nullable=True),
    sa.Column('skill2_level', sa.Integer(), nullable=True),
    sa.Column('skill3_level', sa.Integer(), nullable=True),
    sa.Column('lucky_value', sa.Float(), nullable=False),
    sa.Column('multiplier', sa.Float(), nullable=False),
    sa.Column('multiplier_skill1', sa.Float(), nullable=True),
    sa.Column('multiplier_skill2', sa.Float(), nullable=True),
    sa.Column('multiplier_skill3', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_equipment_cards_card_id'), 'user_equipment_cards', ['card_id'], unique=True)
    op.create_table('user_follows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('follower_id', sa.UUID(), nullable=False),
    sa.Column('followed_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follower_id', 'followed_id', name='uq_follower_followed')
    )
    op.create_table('user_real_name_hk',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', name='gender'), nullable=False),
    sa.Column('birth_date', sa.String(), nullable=False),
    sa.Column('name_Cn', sa.String(), nullable=True),
    sa.Column('name_En', sa.String(), nullable=False),
    sa.Column('card_id', sa.String(), nullable=False),
    sa.Column('name_code', sa.String(), nullable=True),
    sa.Column('issued_code', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('is_display_gender', sa.Boolean(), nullable=False),
    sa.Column('is_display_age', sa.Boolean(), nullable=False),
    sa.Column('is_display_location', sa.Boolean(), nullable=False),
    sa.Column('enable_auto_location', sa.Boolean(), nullable=False),
    sa.Column('is_display_identity', sa.Boolean(), nullable=False),
    sa.Column('default_sport', sa.Enum('running', 'bike', name='sporttype'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_sign_in',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('is_vip', sa.Boolean(), nullable=False),
    sa.Column('sign_in_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'is_vip', 'sign_in_date', name='uq_user_vip_sign_in_date')
    )
    op.create_table('user_subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('auto_renew', sa.Boolean(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('grace_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('apple_original_transaction_id', sa.String(), nullable=True),
    sa.Column('apple_latest_transaction_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_subscriptions_user_id'), 'user_subscriptions', ['user_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('user', 'admin', name='userrole'), nullable=False),
    sa.Column('status', sa.Enum('normal', 'deleted', 'banned', name='userstatus'), nullable=False),
    sa.Column('nickname', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('apple_id', sa.String(), nullable=True),
    sa.Column('apple_email', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('apple_iap_token', sa.UUID(), nullable=False),
    sa.Column('avatar_image_url', sa.String(), nullable=False),
    sa.Column('background_image_url', sa.String(), nullable=False),
    sa.Column('introduction', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('identity_auth_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('phone_number IS NOT NULL OR apple_id IS NOT NULL OR email IS NOT NULL', name='ck_user_phone_or_apple_id_or_email_not_null'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('apple_iap_token')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=True)
    op.create_index('uq_users_apple_id_status', 'users', ['apple_id'], unique=True, postgresql_where=sa.text("status IN ('normal', 'banned')"))
    op.create_index('uq_users_email_status', 'users', ['email'], unique=True, postgresql_where=sa.text("status IN ('normal', 'banned')"))
    op.create_index('uq_users_nickname_status', 'users', ['nickname'], unique=True, postgresql_where=sa.text("status IN ('normal', 'banned')"))
    op.create_index('uq_users_phone_status', 'users', ['phone_number'], unique=True, postgresql_where=sa.text("status IN ('normal', 'banned')"))
    op.create_table('cp_registration_card_defs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sport_type', sa.Enum('running', 'bike', name='sporttype'), nullable=False),
    sa.Column('is_team', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['cp_asset_defs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cp_team_card_defs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sport_type', sa.Enum('running', 'bike', name='sporttype'), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['cp_asset_defs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
