"""optimize_route_training_record_tables

Revision ID: 15da4224ffb1
Revises: 4bf14ab8198b
Create Date: 2026-05-07 23:09:29.340178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '15da4224ffb1'
down_revision: Union[str, None] = '4bf14ab8198b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bike_route_training_records', sa.Column('penalty_seconds', sa.Float(), nullable=False))
    op.alter_column('bike_route_training_records', 'path_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('bike_route_training_records', 'duration_seconds',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('bike_route_training_records', 'local_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('bike_route_training_records', 'settlement_rewards',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    
    op.add_column('running_route_training_records', sa.Column('penalty_seconds', sa.Float(), nullable=False))
    op.alter_column('running_route_training_records', 'path_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('running_route_training_records', 'duration_seconds',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('running_route_training_records', 'local_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('running_route_training_records', 'settlement_rewards',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
