"""add mailbox leaderboard & career_scores table

Revision ID: 16c2690207e5
Revises: 799583d1ea49
Create Date: 2025-09-15 06:10:28.137315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '16c2690207e5'
down_revision: Union[str, None] = '799583d1ea49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bike_career_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('season_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bike_career_scores_season_id'), 'bike_career_scores', ['season_id'], unique=False)
    op.create_index(op.f('ix_bike_career_scores_user_id'), 'bike_career_scores', ['user_id'], unique=False)
    op.create_table('bike_leaderboard',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('track_id', sa.UUID(), nullable=False),
    sa.Column('gender', postgresql.ENUM('male', 'female', name='gender', create_type=False), nullable=False),
    sa.Column('rank_position', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('record_id', sa.String(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('reward', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('track_id', 'gender', 'rank_position', name='uq_bike_track_gender_rank')
    )
    op.create_index(op.f('ix_bike_leaderboard_record_id'), 'bike_leaderboard', ['record_id'], unique=False)
    op.create_index(op.f('ix_bike_leaderboard_track_id'), 'bike_leaderboard', ['track_id'], unique=False)
    op.create_index(op.f('ix_bike_leaderboard_user_id'), 'bike_leaderboard', ['user_id'], unique=False)
    op.create_table('running_career_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('season_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_running_career_scores_season_id'), 'running_career_scores', ['season_id'], unique=False)
    op.create_index(op.f('ix_running_career_scores_user_id'), 'running_career_scores', ['user_id'], unique=False)
    op.create_table('running_leaderboard',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('track_id', sa.UUID(), nullable=False),
    sa.Column('gender', postgresql.ENUM('male', 'female', name='gender', create_type=False), nullable=False),
    sa.Column('rank_position', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('record_id', sa.String(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('reward', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('track_id', 'gender', 'rank_position', name='uq_running_track_gender_rank')
    )
    op.create_index(op.f('ix_running_leaderboard_record_id'), 'running_leaderboard', ['record_id'], unique=False)
    op.create_index(op.f('ix_running_leaderboard_track_id'), 'running_leaderboard', ['track_id'], unique=False)
    op.create_index(op.f('ix_running_leaderboard_user_id'), 'running_leaderboard', ['user_id'], unique=False)

    op.add_column('bike_tracks', sa.Column('score', sa.Integer(), nullable=True))
    op.execute("UPDATE bike_tracks SET score = 500")
    op.alter_column('bike_tracks', 'score', nullable=False)
    op.add_column('running_tracks', sa.Column('score', sa.Integer(), nullable=True))
    op.execute("UPDATE running_tracks SET score = 200")
    op.alter_column('running_tracks', 'score', nullable=False)
    op.alter_column('running_tracks', 'prize_pool',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('running_tracks', 'prize_pool',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('running_tracks', 'score')
    op.drop_column('bike_tracks', 'score')
    op.drop_index(op.f('ix_running_leaderboard_user_id'), table_name='running_leaderboard')
    op.drop_index(op.f('ix_running_leaderboard_track_id'), table_name='running_leaderboard')
    op.drop_index(op.f('ix_running_leaderboard_record_id'), table_name='running_leaderboard')
    op.drop_table('running_leaderboard')
    op.drop_index(op.f('ix_running_career_scores_user_id'), table_name='running_career_scores')
    op.drop_index(op.f('ix_running_career_scores_season_id'), table_name='running_career_scores')
    op.drop_table('running_career_scores')
    op.drop_index(op.f('ix_bike_leaderboard_user_id'), table_name='bike_leaderboard')
    op.drop_index(op.f('ix_bike_leaderboard_track_id'), table_name='bike_leaderboard')
    op.drop_index(op.f('ix_bike_leaderboard_record_id'), table_name='bike_leaderboard')
    op.drop_table('bike_leaderboard')
    op.drop_index(op.f('ix_bike_career_scores_user_id'), table_name='bike_career_scores')
    op.drop_index(op.f('ix_bike_career_scores_season_id'), table_name='bike_career_scores')
    op.drop_table('bike_career_scores')
    # ### end Alembic commands ###
