"""add_route_card_to_cpassettype_enum

Revision ID: 1f173e7a349b
Revises: 262f845cb846
Create Date: 2026-05-09 20:51:46.337514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f173e7a349b'
down_revision: Union[str, None] = '262f845cb846'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new value to cpassettype enum
    op.execute("ALTER TYPE cpassettype ADD VALUE IF NOT EXISTS 'route_card'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
