"""add ad_id to banner_ads table

Revision ID: 21db316dd537
Revises: 3ac9178e570a
Create Date: 2025-12-15 02:41:59.092267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21db316dd537'
down_revision: Union[str, None] = '3ac9178e570a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banner_ads', sa.Column('ad_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_banner_ads_ad_id'), 'banner_ads', ['ad_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_banner_ads_ad_id'), table_name='banner_ads')
    op.drop_column('banner_ads', 'ad_id')
    # ### end Alembic commands ###
