"""add equip_card_price table

Revision ID: 24b5aa2a9a40
Revises: e763b25763f8
Create Date: 2025-08-26 22:15:10.651447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '24b5aa2a9a40'
down_revision: Union[str, None] = 'e763b25763f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equip_card_price',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('def_id', sa.UUID(), nullable=False),
    sa.Column('ccasset_type', postgresql.ENUM('COIN', 'COUPON', 'VOUCHER', name='ccassettype', create_type=False), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('is_on_shelves', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('def_id', name='uix_equip_card_price_def_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('equip_card_price')
    # ### end Alembic commands ###
