"""update users table ( imageurl can not be none )

Revision ID: 25e67424db01
Revises: 5be2de8ac3e4
Create Date: 2025-05-17 03:24:36.116018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25e67424db01'
down_revision: Union[str, None] = '5be2de8ac3e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE users SET avatar_image_url = '' WHERE avatar_image_url IS NULL")
    op.execute("UPDATE users SET background_image_url = '' WHERE background_image_url IS NULL")

    op.alter_column('users', 'avatar_image_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'background_image_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'background_image_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'avatar_image_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
