"""add_route_create_cpasset

Revision ID: 262f845cb846
Revises: 15da4224ffb1
Create Date: 2026-05-09 20:18:31.676941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '262f845cb846'
down_revision: Union[str, None] = '15da4224ffb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cp_route_card_defs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sport_type', postgresql.ENUM('running', 'bike', name='sporttype', create_type=False), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['cp_asset_defs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
