"""enable training_state sys & fix timezone issues

Revision ID: 2b434cebed8b
Revises: 8bb592dad913
Create Date: 2026-03-06 13:44:05.581830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b434cebed8b'
down_revision: Union[str, None] = '8bb592dad913'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_training_states_bike',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('current_value', sa.Integer(), nullable=False),
    sa.Column('last_training_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_decay_date', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_training_states_bike_user_id'), 'user_training_states_bike', ['user_id'], unique=False)

    op.create_table('user_training_states_daily_bike',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'local_date', name='uq_user_training_state_daily_bike_user_date')
    )
    op.create_index(op.f('ix_user_training_states_daily_bike_user_id'), 'user_training_states_daily_bike', ['user_id'], unique=False)

    op.create_table('user_training_states_daily_running',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'local_date', name='uq_user_training_state_daily_running_user_date')
    )
    op.create_index(op.f('ix_user_training_states_daily_running_user_id'), 'user_training_states_daily_running', ['user_id'], unique=False)

    op.create_table('user_training_states_running',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('current_value', sa.Integer(), nullable=False),
    sa.Column('last_training_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_decay_date', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_training_states_running_user_id'), 'user_training_states_running', ['user_id'], unique=False)

    op.add_column('bike_free_training_records', sa.Column('local_date', sa.Date(), nullable=False))
    op.create_index(op.f('ix_bike_free_training_records_local_date'), 'bike_free_training_records', ['local_date'], unique=False)
    
    op.add_column('running_free_training_records', sa.Column('local_date', sa.Date(), nullable=False))
    op.create_index(op.f('ix_running_free_training_records_local_date'), 'running_free_training_records', ['local_date'], unique=False)

    op.add_column('bike_race_records', sa.Column('local_date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_bike_race_records_local_date'), 'bike_race_records', ['local_date'], unique=False)
    op.execute("UPDATE bike_race_records SET local_date = (end_time AT TIME ZONE 'Asia/Shanghai')::date WHERE local_date IS NULL AND end_time IS NOT NULL")
    op.alter_column('bike_race_records', 'local_date', server_default=None)

    op.add_column('running_race_records', sa.Column('local_date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_running_race_records_local_date'), 'running_race_records', ['local_date'], unique=False)
    op.execute("UPDATE running_race_records SET local_date = (end_time AT TIME ZONE 'Asia/Shanghai')::date WHERE local_date IS NULL AND end_time IS NOT NULL")
    op.alter_column('running_race_records', 'local_date', server_default=None)

    op.add_column('users', sa.Column('timezone', sa.String(), server_default='UTC', nullable=True))
    op.execute("UPDATE users SET timezone = 'UTC' WHERE timezone IS NULL")
    op.alter_column('users', 'timezone', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
