"""optimize cascade delete behavior

Revision ID: 2f9ed4b067fc
Revises: 4140b2f2f43c
Create Date: 2025-07-30 03:00:29.108316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f9ed4b067fc'
down_revision: Union[str, None] = '4140b2f2f43c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bike_team_members', 'is_leader',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('bike_team_members', 'is_registered',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bike_team_members', 'is_registered',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('bike_team_members', 'is_leader',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
