"""add region_id in regions table

Revision ID: 323ad8005429
Revises: ae560309c411
Create Date: 2025-12-19 13:27:07.635200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '323ad8005429'
down_revision: Union[str, None] = 'ae560309c411'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('spatial_ref_sys')

    op.add_column('regions', sa.Column('region_id', sa.String(), nullable=True))
    op.execute("UPDATE regions SET region_id = 'CN-SH-SH' WHERE id = '3b6ee698-3f90-45a6-b292-aa75beae8d55'")
    op.execute("UPDATE regions SET region_id = 'CN-BJ-BJ' WHERE id = '30b68bbe-c1ac-431b-829e-4325ac865a6c'")
    op.alter_column('regions', 'region_id', nullable=False)

    op.add_column('regions', sa.Column('boundary', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    #op.create_index('idx_regions_boundary', 'regions', ['boundary'], unique=False, postgresql_using='gist')
    op.execute("""
    CREATE INDEX IF NOT EXISTS idx_regions_boundary
    ON regions USING gist (boundary)
    """)
    op.create_index(op.f('ix_regions_region_id'), 'regions', ['region_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_regions_region_id'), table_name='regions')
    op.drop_index('idx_regions_boundary', table_name='regions', postgresql_using='gist')
    op.drop_column('regions', 'boundary')
    op.drop_column('regions', 'region_id')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###
