"""add user_sign_in & sign_in_reward table

Revision ID: 3274263267b1
Revises: 40bad09dc59d
Create Date: 2025-10-20 03:25:17.534501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3274263267b1'
down_revision: Union[str, None] = '40bad09dc59d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sign_in_rewards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('reward_type', postgresql.ENUM('COIN', 'COUPON', 'VOUCHER', 'STONE1', 'STONE2', 'STONE3', name='ccassettype', create_type=False), nullable=False),
    sa.Column('reward_count', sa.Integer(), nullable=False),
    sa.Column('reward_type_vip', postgresql.ENUM('COIN', 'COUPON', 'VOUCHER', 'STONE1', 'STONE2', 'STONE3', name='ccassettype', create_type=False), nullable=False),
    sa.Column('reward_count_vip', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_sign_in',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('is_vip', sa.Boolean(), nullable=False),
    sa.Column('sign_in_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'is_vip', 'sign_in_date', name='uq_user_vip_sign_in_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_sign_in')
    op.drop_table('sign_in_rewards')
    # ### end Alembic commands ###
