"""add apple_iap_token in users table

Revision ID: 3438f9d2f606
Revises: bfe130e79547
Create Date: 2025-12-05 10:16:33.174132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3438f9d2f606'
down_revision: Union[str, None] = 'bfe130e79547'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('apple_iap_token', sa.UUID(), nullable=True))

    op.execute("UPDATE users SET apple_iap_token = gen_random_uuid() WHERE apple_iap_token IS NULL")
    op.alter_column(
        'users',
        'apple_iap_token',
        nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'apple_iap_token')
    # ### end Alembic commands ###
