"""opt daily_task & task_record table

Revision ID: 38c36d335608
Revises: 13b4bab9d4f3
Create Date: 2025-10-24 06:27:02.541977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '38c36d335608'
down_revision: Union[str, None] = '13b4bab9d4f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bike_daily_task', sa.Column('reward_stage1_type', postgresql.ENUM('COIN', 'COUPON', 'VOUCHER', 'STONE1', 'STONE2', 'STONE3', name='ccassettype', create_type=False), nullable=False))
    op.add_column('bike_daily_task', sa.Column('reward_stage2_type', postgresql.ENUM('COIN', 'COUPON', 'VOUCHER', 'STONE1', 'STONE2', 'STONE3', name='ccassettype', create_type=False), nullable=False))
    op.add_column('bike_daily_task', sa.Column('reward_stage3_id', sa.String(), nullable=False))
    op.alter_column('bike_daily_task', 'reward_stage1',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bike_daily_task', 'reward_stage2',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('bike_daily_task', 'reward_stage3')
    op.add_column('bike_daily_task_records', sa.Column('is_reward1_received', sa.Boolean(), nullable=False))
    op.add_column('bike_daily_task_records', sa.Column('is_reward2_received', sa.Boolean(), nullable=False))
    op.add_column('bike_daily_task_records', sa.Column('is_reward3_received', sa.Boolean(), nullable=False))
    op.add_column('running_daily_task', sa.Column('reward_stage1_type', postgresql.ENUM('COIN', 'COUPON', 'VOUCHER', 'STONE1', 'STONE2', 'STONE3', name='ccassettype', create_type=False), nullable=False))
    op.add_column('running_daily_task', sa.Column('reward_stage2_type', postgresql.ENUM('COIN', 'COUPON', 'VOUCHER', 'STONE1', 'STONE2', 'STONE3', name='ccassettype', create_type=False), nullable=False))
    op.add_column('running_daily_task', sa.Column('reward_stage3_id', sa.String(), nullable=False))
    op.alter_column('running_daily_task', 'reward_stage1',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('running_daily_task', 'reward_stage2',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('running_daily_task', 'reward_stage3')
    op.add_column('running_daily_task_records', sa.Column('is_reward1_received', sa.Boolean(), nullable=False))
    op.add_column('running_daily_task_records', sa.Column('is_reward2_received', sa.Boolean(), nullable=False))
    op.add_column('running_daily_task_records', sa.Column('is_reward3_received', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('running_daily_task_records', 'is_reward3_received')
    op.drop_column('running_daily_task_records', 'is_reward2_received')
    op.drop_column('running_daily_task_records', 'is_reward1_received')
    op.add_column('running_daily_task', sa.Column('reward_stage3', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('running_daily_task', 'reward_stage2',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('running_daily_task', 'reward_stage1',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('running_daily_task', 'reward_stage3_id')
    op.drop_column('running_daily_task', 'reward_stage2_type')
    op.drop_column('running_daily_task', 'reward_stage1_type')
    op.drop_column('bike_daily_task_records', 'is_reward3_received')
    op.drop_column('bike_daily_task_records', 'is_reward2_received')
    op.drop_column('bike_daily_task_records', 'is_reward1_received')
    op.add_column('bike_daily_task', sa.Column('reward_stage3', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('bike_daily_task', 'reward_stage2',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bike_daily_task', 'reward_stage1',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('bike_daily_task', 'reward_stage3_id')
    op.drop_column('bike_daily_task', 'reward_stage2_type')
    op.drop_column('bike_daily_task', 'reward_stage1_type')
    # ### end Alembic commands ###
