"""add validation_score to record table & add toBeVerified to recordstatus

Revision ID: 3abbca4dd41b
Revises: cb7906842dae
Create Date: 2025-11-13 16:33:56.488306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '3abbca4dd41b'
down_revision: Union[str, None] = 'cb7906842dae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE recordstatus ADD VALUE IF NOT EXISTS 'toBeVerified'")
    op.add_column('bike_race_records', sa.Column('validation_score', sa.Float(), nullable=True))
    op.add_column('running_race_records', sa.Column('validation_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('running_race_records', 'validation_score')
    op.drop_column('bike_race_records', 'validation_score')
    # ### end Alembic commands ###
