"""add_route_ranklist_table

Revision ID: 3b2e2056fd9b
Revises: 1f173e7a349b
Create Date: 2026-05-11 16:48:30.148495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '3b2e2056fd9b'
down_revision: Union[str, None] = '1f173e7a349b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bike_route_ranklists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('route_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('gender', postgresql.ENUM('male', 'female', name='gender', create_type=False), nullable=False),
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('route_id', 'user_id', name='uq_bike_route_ranklist_route_user')
    )
    op.create_index('idx_bike_route_ranklist_route_score', 'bike_route_ranklists', ['route_id', 'gender', 'duration_seconds', 'user_id'], unique=False)
    op.create_index(op.f('ix_bike_route_ranklists_route_id'), 'bike_route_ranklists', ['route_id'], unique=False)

    op.create_table('running_route_ranklists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('route_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('gender', postgresql.ENUM('male', 'female', name='gender', create_type=False), nullable=False),
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('route_id', 'user_id', name='uq_running_route_ranklist_route_user')
    )
    op.create_index('idx_running_route_ranklist_route_score', 'running_route_ranklists', ['route_id', 'gender', 'duration_seconds', 'user_id'], unique=False)
    op.create_index(op.f('ix_running_route_ranklists_route_id'), 'running_route_ranklists', ['route_id'], unique=False)

    op.create_index('idx_bike_route_training_records_route_user', 'bike_route_training_records', ['route_id', 'user_id'], unique=False)
    op.create_index('idx_running_route_training_records_route_user', 'running_route_training_records', ['route_id', 'user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
