"""change record_id type in leaderboard table

Revision ID: 4073f0cae353
Revises: 16c2690207e5
Create Date: 2025-09-15 21:00:43.400666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4073f0cae353'
down_revision: Union[str, None] = '16c2690207e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bike_leaderboard', 'record_id',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using='record_id::uuid'
               )
    op.alter_column('running_leaderboard', 'record_id',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using='record_id::uuid'
               )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('running_leaderboard', 'record_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('bike_leaderboard', 'record_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
