"""add updated_at in realname table

Revision ID: 40bad09dc59d
Revises: 6dee4bbeda10
Create Date: 2025-10-14 03:49:14.013535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40bad09dc59d'
down_revision: Union[str, None] = '6dee4bbeda10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_real_name_hk', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('user_real_name_hk', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_real_name_hk', 'updated_at')
    op.drop_column('user_real_name_hk', 'created_at')
    # ### end Alembic commands ###
