"""delete is_locked to bike_teams table

Revision ID: 4140b2f2f43c
Revises: b82d3c5800e8
Create Date: 2025-07-24 15:12:21.478860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4140b2f2f43c'
down_revision: Union[str, None] = 'b82d3c5800e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bike_teams', 'is_locked')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bike_teams', sa.Column('is_locked', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
