"""add_training_route_record_tables

Revision ID: 4667ac2e5884
Revises: f131e4059432
Create Date: 2026-04-27 17:11:46.274702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4667ac2e5884'
down_revision: Union[str, None] = 'f131e4059432'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bike_route_training_paths',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('path_id', sa.String(), nullable=False),
    sa.Column('path', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bike_route_training_paths_path_id'), 'bike_route_training_paths', ['path_id'], unique=True)

    op.create_table('bike_route_training_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('record_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('route_id', sa.UUID(), nullable=False),
    sa.Column('path_id', sa.UUID(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('local_date', sa.Date(), nullable=True),
    sa.Column('settlement_rewards', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bike_route_training_records_local_date'), 'bike_route_training_records', ['local_date'], unique=False)
    op.create_index(op.f('ix_bike_route_training_records_record_id'), 'bike_route_training_records', ['record_id'], unique=True)

    op.create_table('card_bonus_in_bike_route_training_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('bonus_ratio', sa.Float(), nullable=True),
    sa.Column('bonus_time', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('card_bonus_in_running_route_training_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('bonus_ratio', sa.Float(), nullable=True),
    sa.Column('bonus_time', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('running_route_training_paths',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('path_id', sa.String(), nullable=False),
    sa.Column('path', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_running_route_training_paths_path_id'), 'running_route_training_paths', ['path_id'], unique=True)
    op.create_table('running_route_training_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('record_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('route_id', sa.UUID(), nullable=False),
    sa.Column('path_id', sa.UUID(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('local_date', sa.Date(), nullable=True),
    sa.Column('settlement_rewards', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_running_route_training_records_local_date'), 'running_route_training_records', ['local_date'], unique=False)
    op.create_index(op.f('ix_running_route_training_records_record_id'), 'running_route_training_records', ['record_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
