"""add_ispremium_to_route_tables

Revision ID: 4bf14ab8198b
Revises: 4667ac2e5884
Create Date: 2026-04-28 16:58:33.887275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bf14ab8198b'
down_revision: Union[str, None] = '4667ac2e5884'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bike_training_routes', sa.Column('is_premium', sa.Boolean(), nullable=True))
    op.execute("UPDATE bike_training_routes SET is_premium = True")
    op.alter_column('bike_training_routes', 'is_premium', nullable=False)

    op.add_column('running_training_routes', sa.Column('is_premium', sa.Boolean(), nullable=True))
    op.execute("UPDATE running_training_routes SET is_premium = True")
    op.alter_column('running_training_routes', 'is_premium', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
