"""add_buff_grids_table

Revision ID: 515edde6efe1
Revises: 3b2e2056fd9b
Create Date: 2026-05-13 05:27:45.048041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '515edde6efe1'
down_revision: Union[str, None] = '3b2e2056fd9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    grideffecttype = sa.Enum(
        'buff', 'debuff',
       name='grideffecttype'
    )
    grideffecttype.create(op.get_bind(), checkfirst=True)

    op.create_table('bike_effect_grid_tile_aggs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('active_date', sa.Date(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('grid_x', sa.Integer(), nullable=False),
    sa.Column('grid_y', sa.Integer(), nullable=False),
    sa.Column('grid_previews', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('active_date', 'level', 'grid_x', 'grid_y', name='uq_bike_effect_grid_tile_aggs_level_grid_date')
    )
    op.create_index(op.f('ix_bike_effect_grid_tile_aggs_active_date'), 'bike_effect_grid_tile_aggs', ['active_date'], unique=False)

    op.create_table('bike_effect_grids',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('region_id', sa.UUID(), nullable=False),
    sa.Column('grid_x', sa.Integer(), nullable=False),
    sa.Column('grid_y', sa.Integer(), nullable=False),
    sa.Column('effect_type', postgresql.ENUM('buff', 'debuff', name='grideffecttype', create_type=False), nullable=False),
    sa.Column('condition_type', sa.String(), nullable=False),
    sa.Column('condition_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reward_type', sa.String(), nullable=False),
    sa.Column('reward_count', sa.Integer(), nullable=False),
    sa.Column('active_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grid_x', 'grid_y', 'active_date', name='uq_bike_effect_grids_grid_date')
    )
    op.create_index(op.f('ix_bike_effect_grids_active_date'), 'bike_effect_grids', ['active_date'], unique=False)
    op.create_index(op.f('ix_bike_effect_grids_region_id'), 'bike_effect_grids', ['region_id'], unique=False)

    op.create_table('bike_effect_grids_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('grid_x', sa.Integer(), nullable=False),
    sa.Column('grid_y', sa.Integer(), nullable=False),
    sa.Column('active_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'grid_x', 'grid_y', 'active_date', name='uq_bike_effect_grids_history_user_grid_date')
    )
    op.create_index(op.f('ix_bike_effect_grids_history_active_date'), 'bike_effect_grids_history', ['active_date'], unique=False)
    op.create_index(op.f('ix_bike_effect_grids_history_user_id'), 'bike_effect_grids_history', ['user_id'], unique=False)

    op.create_table('running_effect_grid_tile_aggs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('active_date', sa.Date(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('grid_x', sa.Integer(), nullable=False),
    sa.Column('grid_y', sa.Integer(), nullable=False),
    sa.Column('grid_previews', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('active_date', 'level', 'grid_x', 'grid_y', name='uq_running_effect_grid_tile_aggs_level_grid_date')
    )
    op.create_index(op.f('ix_running_effect_grid_tile_aggs_active_date'), 'running_effect_grid_tile_aggs', ['active_date'], unique=False)

    op.create_table('running_effect_grids',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('region_id', sa.UUID(), nullable=False),
    sa.Column('grid_x', sa.Integer(), nullable=False),
    sa.Column('grid_y', sa.Integer(), nullable=False),
    sa.Column('effect_type', postgresql.ENUM('buff', 'debuff', name='grideffecttype', create_type=False), nullable=False),
    sa.Column('condition_type', sa.String(), nullable=False),
    sa.Column('condition_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reward_type', sa.String(), nullable=False),
    sa.Column('reward_count', sa.Integer(), nullable=False),
    sa.Column('active_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grid_x', 'grid_y', 'active_date', name='uq_running_effect_grids_grid_date')
    )
    op.create_index(op.f('ix_running_effect_grids_active_date'), 'running_effect_grids', ['active_date'], unique=False)
    op.create_index(op.f('ix_running_effect_grids_region_id'), 'running_effect_grids', ['region_id'], unique=False)

    op.create_table('running_effect_grids_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('grid_x', sa.Integer(), nullable=False),
    sa.Column('grid_y', sa.Integer(), nullable=False),
    sa.Column('active_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'grid_x', 'grid_y', 'active_date', name='uq_running_effect_grids_history_user_grid_date')
    )
    op.create_index(op.f('ix_running_effect_grids_history_active_date'), 'running_effect_grids_history', ['active_date'], unique=False)
    op.create_index(op.f('ix_running_effect_grids_history_user_id'), 'running_effect_grids_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
