"""add country_code property to regions table

Revision ID: 532e4b63f6a5
Revises: a79f612c0ccf
Create Date: 2025-06-18 23:34:50.636484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '532e4b63f6a5'
down_revision: Union[str, None] = 'a79f612c0ccf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regions', sa.Column('country_code', sa.String(), nullable=True))
    op.execute("UPDATE regions SET country_code = 'CN'")
    op.alter_column('regions', 'country_code', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('regions', 'country_code')
    # ### end Alembic commands ###
