"""add status to users table & delete all foreignkeys

Revision ID: 548426b9a0a2
Revises: 13d0242e713f
Create Date: 2025-07-19 04:41:20.676832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '548426b9a0a2'
down_revision: Union[str, None] = '13d0242e713f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bike_race_records_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('record_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('track_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bike_race_records_history_record_id'), 'bike_race_records_history', ['record_id'], unique=True)
    op.create_table('bike_team_members_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('is_leader', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_bans_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('banned_times', sa.Integer(), nullable=False),
    sa.Column('unban_time', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('bike_events_season_id_fkey', 'bike_events', type_='foreignkey')
    op.drop_constraint('bike_events_region_id_fkey', 'bike_events', type_='foreignkey')
    op.add_column('bike_race_records', sa.Column('team_id', sa.UUID(), nullable=True))
    op.drop_constraint('bike_race_records_track_id_fkey', 'bike_race_records', type_='foreignkey')
    op.drop_constraint('bike_race_records_user_id_fkey', 'bike_race_records', type_='foreignkey')
    op.drop_column('bike_race_records', 'is_team')
    op.drop_column('bike_race_records', 'team_code')
    op.drop_constraint('bike_team_applied_members_team_id_fkey', 'bike_team_applied_members', type_='foreignkey')
    op.drop_constraint('bike_team_applied_members_user_id_fkey', 'bike_team_applied_members', type_='foreignkey')
    op.drop_constraint('bike_team_members_team_id_fkey', 'bike_team_members', type_='foreignkey')
    op.drop_constraint('bike_team_members_user_id_fkey', 'bike_team_members', type_='foreignkey')
    op.drop_constraint('bike_teams_track_id_fkey', 'bike_teams', type_='foreignkey')
    op.drop_constraint('bike_tracks_event_id_fkey', 'bike_tracks', type_='foreignkey')
    op.drop_constraint('ccasset_transactions_user_id_fkey', 'ccasset_transactions', type_='foreignkey')
    op.drop_constraint('cpasset_price_prop_def_id_fkey', 'cpasset_price', type_='foreignkey')
    op.drop_constraint('cpasset_transactions_prop_def_id_fkey', 'cpasset_transactions', type_='foreignkey')
    op.drop_constraint('cpasset_transactions_user_id_fkey', 'cpasset_transactions', type_='foreignkey')
    op.drop_constraint('running_events_season_id_fkey', 'running_events', type_='foreignkey')
    op.drop_constraint('running_events_region_id_fkey', 'running_events', type_='foreignkey')
    op.add_column('running_race_records', sa.Column('team_id', sa.UUID(), nullable=True))
    op.drop_constraint('running_race_records_track_id_fkey', 'running_race_records', type_='foreignkey')
    op.drop_constraint('running_race_records_user_id_fkey', 'running_race_records', type_='foreignkey')
    op.drop_column('running_race_records', 'is_team')
    op.drop_column('running_race_records', 'team_code')
    op.drop_constraint('running_tracks_event_id_fkey', 'running_tracks', type_='foreignkey')
    op.drop_constraint('user_ccassets_user_id_fkey', 'user_ccassets', type_='foreignkey')
    op.drop_constraint('user_cpassets_user_id_fkey', 'user_cpassets', type_='foreignkey')
    op.drop_constraint('user_cpassets_prop_def_id_fkey', 'user_cpassets', type_='foreignkey')
    op.drop_constraint('user_equipment_cards_user_id_fkey', 'user_equipment_cards', type_='foreignkey')
    op.drop_constraint('user_equipment_cards_equipment_def_id_fkey', 'user_equipment_cards', type_='foreignkey')
    op.drop_constraint('user_follows_followed_id_fkey', 'user_follows', type_='foreignkey')
    op.drop_constraint('user_follows_follower_id_fkey', 'user_follows', type_='foreignkey')
    op.execute("CREATE TYPE userstatus AS ENUM ('normal', 'deleted', 'banned')")
    op.add_column('users', sa.Column('status', sa.Enum('normal', 'deleted', 'banned', name='userstatus'), nullable=True))
    op.execute("UPDATE users SET status = 'normal'")
    op.alter_column('users', 'status', nullable=False)
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'status')
    op.create_foreign_key('user_follows_follower_id_fkey', 'user_follows', 'users', ['follower_id'], ['id'])
    op.create_foreign_key('user_follows_followed_id_fkey', 'user_follows', 'users', ['followed_id'], ['id'])
    op.create_foreign_key('user_equipment_cards_equipment_def_id_fkey', 'user_equipment_cards', 'equipment_card_defs', ['equipment_def_id'], ['id'])
    op.create_foreign_key('user_equipment_cards_user_id_fkey', 'user_equipment_cards', 'users', ['user_id'], ['id'])
    op.create_foreign_key('user_cpassets_prop_def_id_fkey', 'user_cpassets', 'cp_asset_defs', ['prop_def_id'], ['id'])
    op.create_foreign_key('user_cpassets_user_id_fkey', 'user_cpassets', 'users', ['user_id'], ['id'])
    op.create_foreign_key('user_ccassets_user_id_fkey', 'user_ccassets', 'users', ['user_id'], ['id'])
    op.create_foreign_key('running_tracks_event_id_fkey', 'running_tracks', 'running_events', ['event_id'], ['id'], ondelete='CASCADE')
    op.add_column('running_race_records', sa.Column('team_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('running_race_records', sa.Column('is_team', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_foreign_key('running_race_records_user_id_fkey', 'running_race_records', 'users', ['user_id'], ['id'])
    op.create_foreign_key('running_race_records_track_id_fkey', 'running_race_records', 'running_tracks', ['track_id'], ['id'])
    op.drop_column('running_race_records', 'team_id')
    op.create_foreign_key('running_events_region_id_fkey', 'running_events', 'regions', ['region_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('running_events_season_id_fkey', 'running_events', 'running_seasons', ['season_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('cpasset_transactions_user_id_fkey', 'cpasset_transactions', 'users', ['user_id'], ['id'])
    op.create_foreign_key('cpasset_transactions_prop_def_id_fkey', 'cpasset_transactions', 'cp_asset_defs', ['prop_def_id'], ['id'])
    op.create_foreign_key('cpasset_price_prop_def_id_fkey', 'cpasset_price', 'cp_asset_defs', ['prop_def_id'], ['id'])
    op.create_foreign_key('ccasset_transactions_user_id_fkey', 'ccasset_transactions', 'users', ['user_id'], ['id'])
    op.create_foreign_key('bike_tracks_event_id_fkey', 'bike_tracks', 'bike_events', ['event_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('bike_teams_track_id_fkey', 'bike_teams', 'bike_tracks', ['track_id'], ['id'])
    op.create_foreign_key('bike_team_members_user_id_fkey', 'bike_team_members', 'users', ['user_id'], ['id'])
    op.create_foreign_key('bike_team_members_team_id_fkey', 'bike_team_members', 'bike_teams', ['team_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('bike_team_applied_members_user_id_fkey', 'bike_team_applied_members', 'users', ['user_id'], ['id'])
    op.create_foreign_key('bike_team_applied_members_team_id_fkey', 'bike_team_applied_members', 'bike_teams', ['team_id'], ['id'], ondelete='CASCADE')
    op.add_column('bike_race_records', sa.Column('team_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('bike_race_records', sa.Column('is_team', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_foreign_key('bike_race_records_user_id_fkey', 'bike_race_records', 'users', ['user_id'], ['id'])
    op.create_foreign_key('bike_race_records_track_id_fkey', 'bike_race_records', 'bike_tracks', ['track_id'], ['id'])
    op.drop_column('bike_race_records', 'team_id')
    op.create_foreign_key('bike_events_region_id_fkey', 'bike_events', 'regions', ['region_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('bike_events_season_id_fkey', 'bike_events', 'bike_seasons', ['season_id'], ['id'], ondelete='CASCADE')
    op.drop_table('user_bans_history')
    op.drop_table('bike_team_members_history')
    op.drop_index(op.f('ix_bike_race_records_history_record_id'), table_name='bike_race_records_history')
    op.drop_table('bike_race_records_history')
    # ### end Alembic commands ###
