"""delete_country_grid_cells_and_region_grid_cells_table

Revision ID: 644b82ce2949
Revises: 81d233e73320
Create Date: 2026-04-10 08:03:21.787184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '644b82ce2949'
down_revision: Union[str, None] = '81d233e73320'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_country_grid_cells_country_code'), table_name='country_grid_cells')
    op.drop_table('country_grid_cells')
    op.drop_index(op.f('ix_region_grid_cells_grid_id'), table_name='region_grid_cells')
    op.drop_index(op.f('ix_region_grid_cells_region_id'), table_name='region_grid_cells')
    op.drop_table('region_grid_cells')

    op.execute('''
    TRUNCATE user_grid_familiarity_bike;
    TRUNCATE user_grid_familiarity_running;
    TRUNCATE user_grid_familiarity_bike_agg;
    TRUNCATE user_grid_familiarity_running_agg;
    ''')

    op.add_column('user_grid_familiarity_bike', sa.Column('region_id', sa.UUID(), nullable=False))
    op.add_column('user_grid_familiarity_bike', sa.Column('grid_x', sa.Integer(), nullable=False))
    op.add_column('user_grid_familiarity_bike', sa.Column('grid_y', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_user_grid_familiarity_bike_grid_id'), table_name='user_grid_familiarity_bike')
    op.drop_constraint(op.f('uq_season_user_grid_familiarity_bike'), 'user_grid_familiarity_bike', type_='unique')
    op.create_index(op.f('ix_user_grid_familiarity_bike_region_id'), 'user_grid_familiarity_bike', ['region_id'], unique=False)
    op.create_unique_constraint('uq_user_grid_familiarity_bike_season_user_grid', 'user_grid_familiarity_bike', ['season_id', 'user_id', 'grid_x', 'grid_y'])
    op.drop_column('user_grid_familiarity_bike', 'grid_id')

    op.add_column('user_grid_familiarity_running', sa.Column('region_id', sa.UUID(), nullable=False))
    op.add_column('user_grid_familiarity_running', sa.Column('grid_x', sa.Integer(), nullable=False))
    op.add_column('user_grid_familiarity_running', sa.Column('grid_y', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_user_grid_familiarity_running_grid_id'), table_name='user_grid_familiarity_running')
    op.drop_constraint(op.f('uq_season_user_grid_familiarity_running'), 'user_grid_familiarity_running', type_='unique')
    op.create_index(op.f('ix_user_grid_familiarity_running_region_id'), 'user_grid_familiarity_running', ['region_id'], unique=False)
    op.create_unique_constraint('uq_user_grid_familiarity_running_season_user_grid', 'user_grid_familiarity_running', ['season_id', 'user_id', 'grid_x', 'grid_y'])
    op.drop_column('user_grid_familiarity_running', 'grid_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
