"""change UniqueConstraint to career_scores

Revision ID: 67a2e11555fe
Revises: 91638a7763c7
Create Date: 2025-09-22 07:19:23.547984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67a2e11555fe'
down_revision: Union[str, None] = '91638a7763c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_bike_career_score_season_gender_user', 'bike_career_scores', type_='unique')
    op.create_unique_constraint('uq_bike_career_score_season_user', 'bike_career_scores', ['season_id', 'user_id'])
    op.drop_constraint('uq_running_career_score_season_gender_user', 'running_career_scores', type_='unique')
    op.create_unique_constraint('uq_running_career_score_season_user', 'running_career_scores', ['season_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_running_career_score_season_user', 'running_career_scores', type_='unique')
    op.create_unique_constraint('uq_running_career_score_season_gender_user', 'running_career_scores', ['season_id', 'gender', 'user_id'])
    op.drop_constraint('uq_bike_career_score_season_user', 'bike_career_scores', type_='unique')
    op.create_unique_constraint('uq_bike_career_score_season_gender_user', 'bike_career_scores', ['season_id', 'gender', 'user_id'])
    # ### end Alembic commands ###
