"""change user_id to unique in realname & setting table

Revision ID: 6cb93d218e07
Revises: cc57762de91c
Create Date: 2025-10-01 20:11:41.905669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cb93d218e07'
down_revision: Union[str, None] = 'cc57762de91c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user_real_name_hk', ['user_id'])
    op.create_unique_constraint(None, 'user_settings', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_settings', type_='unique')
    op.drop_constraint(None, 'user_real_name_hk', type_='unique')
    # ### end Alembic commands ###
