"""delete type_name in equipment_card_defs table

Revision ID: 6cd242d2e002
Revises: 0fddd560bf0e
Create Date: 2025-11-18 20:25:38.741449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cd242d2e002'
down_revision: Union[str, None] = '0fddd560bf0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipment_card_defs', 'type_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment_card_defs', sa.Column('type_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
