"""add career_statistic_data table

Revision ID: 6dee4bbeda10
Revises: c08a875c49c1
Create Date: 2025-10-14 00:32:02.374134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dee4bbeda10'
down_revision: Union[str, None] = 'c08a875c49c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bike_career_statistic_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('season_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('total_distance', sa.Float(), nullable=False),
    sa.Column('total_time', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id', 'user_id', name='uq_bike_career_statistic_season_user')
    )
    op.create_index(op.f('ix_bike_career_statistic_data_season_id'), 'bike_career_statistic_data', ['season_id'], unique=False)
    op.create_index(op.f('ix_bike_career_statistic_data_user_id'), 'bike_career_statistic_data', ['user_id'], unique=False)

    op.create_table('running_career_statistic_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('season_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('total_distance', sa.Float(), nullable=False),
    sa.Column('total_time', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id', 'user_id', name='uq_running_career_statistic_season_user')
    )
    op.create_index(op.f('ix_running_career_statistic_data_season_id'), 'running_career_statistic_data', ['season_id'], unique=False)
    op.create_index(op.f('ix_running_career_statistic_data_user_id'), 'running_career_statistic_data', ['user_id'], unique=False)
    # 为兼容历史数据，新增列采用三步：先可空 -> 回填 -> 设默认+非空
    # bike_career_scores.voucher_bonus
    op.add_column('bike_career_scores', sa.Column('voucher_bonus', sa.Integer(), nullable=True))
    op.execute("UPDATE bike_career_scores SET voucher_bonus = 0 WHERE voucher_bonus IS NULL")
    op.alter_column(
        'bike_career_scores',
        'voucher_bonus',
        nullable=False
    )
    # running_career_scores.voucher_bonus
    op.add_column('running_career_scores', sa.Column('voucher_bonus', sa.Integer(), nullable=True))
    op.execute("UPDATE running_career_scores SET voucher_bonus = 0 WHERE voucher_bonus IS NULL")
    op.alter_column(
        'running_career_scores',
        'voucher_bonus',
        nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('running_career_scores', 'voucher_bonus')
    op.drop_column('bike_career_scores', 'voucher_bonus')
    op.drop_index(op.f('ix_running_career_statistic_data_user_id'), table_name='running_career_statistic_data')
    op.drop_index(op.f('ix_running_career_statistic_data_season_id'), table_name='running_career_statistic_data')
    op.drop_table('running_career_statistic_data')
    op.drop_index(op.f('ix_bike_career_statistic_data_user_id'), table_name='bike_career_statistic_data')
    op.drop_index(op.f('ix_bike_career_statistic_data_season_id'), table_name='bike_career_statistic_data')
    op.drop_table('bike_career_statistic_data')
    # ### end Alembic commands ###
