"""add card_id in bonus_by_team_members table

Revision ID: 6f451b1f4a3b
Revises: c8e601be0a82
Create Date: 2026-01-20 16:10:28.914457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f451b1f4a3b'
down_revision: Union[str, None] = 'c8e601be0a82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bike_bonus_by_team_members', sa.Column('card_id', sa.UUID(), nullable=True))
    op.execute(
        """
        UPDATE bike_bonus_by_team_members
        SET card_id = gen_random_uuid()
        WHERE card_id IS NULL;
        """
    )
    op.alter_column("bike_bonus_by_team_members", "card_id", nullable=False)

    op.add_column('running_bonus_by_team_members', sa.Column('card_id', sa.UUID(), nullable=True))
    op.execute(
        """
        UPDATE running_bonus_by_team_members
        SET card_id = gen_random_uuid()
        WHERE card_id IS NULL;
        """
    )
    op.alter_column("running_bonus_by_team_members", "card_id", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('running_bonus_by_team_members', 'card_id')
    op.drop_column('bike_bonus_by_team_members', 'card_id')
    # ### end Alembic commands ###
