"""delete validation_token in equipment_card_def table

Revision ID: 750c5dc73b19
Revises: 6f451b1f4a3b
Create Date: 2026-01-21 12:08:58.207395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '750c5dc73b19'
down_revision: Union[str, None] = '6f451b1f4a3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipment_card_defs', 'validation_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment_card_defs', sa.Column('validation_token', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
