"""optimize user_equipment_cards table

Revision ID: 772c48eb3749
Revises: 9b09927988bf
Create Date: 2025-09-10 19:51:19.920810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '772c48eb3749'
down_revision: Union[str, None] = '9b09927988bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE ccassettype ADD VALUE IF NOT EXISTS 'STONE1'")
    op.execute("ALTER TYPE ccassettype ADD VALUE IF NOT EXISTS 'STONE2'")
    op.execute("ALTER TYPE ccassettype ADD VALUE IF NOT EXISTS 'STONE3'")

    op.create_table('user_equipment_cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('equipment_def_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('skill1_level', sa.Integer(), nullable=True),
    sa.Column('skill2_level', sa.Integer(), nullable=True),
    sa.Column('skill3_level', sa.Integer(), nullable=True),
    sa.Column('lucky_value', sa.Float(), nullable=False),
    sa.Column('multiplier', sa.Float(), nullable=False),
    sa.Column('multiplier_skill1', sa.Float(), nullable=True),
    sa.Column('multiplier_skill2', sa.Float(), nullable=True),
    sa.Column('multiplier_skill3', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_equipment_cards_card_id'), 'user_equipment_cards', ['card_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_equipment_cards_card_id'), table_name='user_equipment_cards')
    op.drop_table('user_equipment_cards')
    # ### end Alembic commands ###
