"""add default_sport to table users

Revision ID: 799583d1ea49
Revises: d57e5a8144b6
Create Date: 2025-09-14 23:30:48.917033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '799583d1ea49'
down_revision: Union[str, None] = 'd57e5a8144b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('default_sport', postgresql.ENUM('running', 'bike', name='sporttype', create_type=False), nullable=True))
    op.execute("UPDATE users SET default_sport = 'bike'::sporttype")
    op.alter_column('users', 'default_sport', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'default_sport')
    # ### end Alembic commands ###
