"""delete_country_code_in_agg

Revision ID: 7afb0f008e90
Revises: f420d9f5ef7b
Create Date: 2026-04-05 00:34:02.572102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7afb0f008e90'
down_revision: Union[str, None] = 'f420d9f5ef7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_grid_familiarity_bike_agg_country_code'), table_name='user_grid_familiarity_bike_agg')
    op.drop_constraint(op.f('uq_user_grid_familiarity_bike_agg_season_user_country_grid'), 'user_grid_familiarity_bike_agg', type_='unique')
    op.create_unique_constraint('uq_user_grid_familiarity_bike_agg_season_user_level_grid', 'user_grid_familiarity_bike_agg', ['season_id', 'user_id', 'level', 'grid_x', 'grid_y'])
    op.drop_column('user_grid_familiarity_bike_agg', 'country_code')
    
    op.drop_index(op.f('ix_user_grid_familiarity_running_agg_country_code'), table_name='user_grid_familiarity_running_agg')
    op.drop_constraint(op.f('uq_user_grid_familiarity_running_agg_season_user_country_grid'), 'user_grid_familiarity_running_agg', type_='unique')
    op.create_unique_constraint('uq_user_grid_familiarity_running_agg_season_user_level_grid', 'user_grid_familiarity_running_agg', ['season_id', 'user_id', 'level', 'grid_x', 'grid_y'])
    op.drop_column('user_grid_familiarity_running_agg', 'country_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # ### end Alembic commands ###
