"""optimize users & user_real_name

Revision ID: 7bbe44da2748
Revises: c28e211d0ea3
Create Date: 2025-10-01 00:29:20.719063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bbe44da2748'
down_revision: Union[str, None] = 'c28e211d0ea3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_real_name', 'birth_date')
    op.add_column('users', sa.Column('birthday', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'birthday')
    op.add_column('user_real_name', sa.Column('birth_date', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
