"""delete_geom_in_country_grid_cells

Revision ID: 81d233e73320
Revises: 7afb0f008e90
Create Date: 2026-04-10 00:21:27.316476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81d233e73320'
down_revision: Union[str, None] = '7afb0f008e90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_country_grid_cells_geom'), table_name='country_grid_cells', postgresql_using='gist')
    op.drop_column('country_grid_cells', 'geom')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
