"""optimize user_realname_identities table

Revision ID: 826f74cd155f
Revises: bae842227238
Create Date: 2026-03-17 08:59:22.797387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '826f74cd155f'
down_revision: Union[str, None] = 'bae842227238'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1️⃣ 重命名表
    op.rename_table('user_real_name_hk', 'user_realname_identities')

    # 2️⃣ 新增字段
    op.add_column('user_realname_identities',
        sa.Column('country_code', sa.String(), nullable=True)
    )
    op.add_column('user_realname_identities',
        sa.Column('card_id_hash', sa.String(), nullable=True)
    )

    # 3️⃣ 填充默认值
    op.execute("""
        UPDATE user_realname_identities
        SET country_code = 'HK'
    """)
    #op.execute("""
    #    UPDATE user_realname_identities
    #    SET card_id_hash = encode(digest(card_id, 'sha256'), 'hex')
    #""")

    # 4️⃣ 改成 NOT NULL
    op.alter_column('user_realname_identities', 'country_code', nullable=False)

    # 5️⃣ 删除旧字段（如果有）
    op.drop_column('user_realname_identities', 'card_id')
    op.drop_column('user_realname_identities', 'name_Cn')
    op.drop_column('user_realname_identities', 'name_En')
    op.drop_column('user_realname_identities', 'name_code')
    op.drop_column('user_realname_identities', 'issued_code')

    # 6️⃣ 添加约束（如果没有）
    op.create_unique_constraint(
        'uq_user_realname_identities_card_id_hash',
        'user_realname_identities',
        ['card_id_hash']
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
