"""add distance to bike_tracks table

Revision ID: 836c94b04e1a
Revises: e0beb968e3c3
Create Date: 2026-01-16 07:54:24.241774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '836c94b04e1a'
down_revision: Union[str, None] = 'e0beb968e3c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bike_tracks', sa.Column('distance', sa.Float(), nullable=True))
    op.execute(
        """
        UPDATE bike_tracks
        SET distance = 5.55
        WHERE distance IS NULL;
        """
    )
    op.alter_column("bike_tracks", "distance", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bike_tracks', 'distance')
    # ### end Alembic commands ###
