"""enable i18n in mailbox table

Revision ID: 84b1b4f080b6
Revises: 4baac5f3227c
Create Date: 2026-01-09 22:30:25.839469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '84b1b4f080b6'
down_revision: Union[str, None] = '4baac5f3227c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mailbox', sa.Column('title_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('mailbox', sa.Column('content_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    op.execute(
        """
        UPDATE mailbox
        SET
            title_i18n = jsonb_build_object('zh-Hans', title),
            content_i18n = CASE
                WHEN content IS NOT NULL
                THEN jsonb_build_object('zh-Hans', content)
                ELSE NULL
            END
        WHERE title_i18n IS NULL;
        """
    )

    op.drop_column('mailbox', 'content')
    op.drop_column('mailbox', 'title')

    op.alter_column("mailbox", "title_i18n", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mailbox', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('mailbox', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('mailbox', 'content_i18n')
    op.drop_column('mailbox', 'title_i18n')
    # ### end Alembic commands ###
