"""add familiarity_time & training_state_time to records

Revision ID: 861e5fec3205
Revises: 8aa189e3635a
Create Date: 2026-03-09 17:36:37.548217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '861e5fec3205'
down_revision: Union[str, None] = '8aa189e3635a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bike_race_records', sa.Column('familiarity_time', sa.Float(), nullable=True))
    op.add_column('bike_race_records', sa.Column('training_state_time', sa.Float(), nullable=True))
    op.add_column('running_race_records', sa.Column('familiarity_time', sa.Float(), nullable=True))
    op.add_column('running_race_records', sa.Column('training_state_time', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
