"""add cpasset_price table

Revision ID: 8a76009cd2ce
Revises: 152275672bab
Create Date: 2025-07-02 03:52:41.803437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '8a76009cd2ce'
down_revision: Union[str, None] = '152275672bab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cpasset_price',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prop_def_id', sa.UUID(), nullable=False),
    sa.Column('ccasset_type', postgresql.ENUM('COIN', 'COUPON', 'VOUCHER', name='ccassettype', create_type=False), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['prop_def_id'], ['cp_asset_defs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prop_def_id', name='uix_cpasset_price_prop_def_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cpasset_price')
    # ### end Alembic commands ###
