"""add settlements jsonb to records tables

Revision ID: 8aa189e3635a
Revises: 2b434cebed8b
Create Date: 2026-03-08 10:07:20.487199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8aa189e3635a'
down_revision: Union[str, None] = '2b434cebed8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bike_free_training_records', sa.Column('settlement_rewards', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('bike_race_records', sa.Column('settlement_rewards', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('running_free_training_records', sa.Column('settlement_rewards', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('running_race_records', sa.Column('settlement_rewards', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
