"""enable free training mode

Revision ID: 8bb592dad913
Revises: 15558fadf600
Create Date: 2026-03-03 19:27:49.628963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = '8bb592dad913'
down_revision: Union[str, None] = '15558fadf600'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bike_free_training_paths',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('path_id', sa.String(), nullable=False),
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('path', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bike_free_training_paths_path_id'), 'bike_free_training_paths', ['path_id'], unique=True)
    op.create_table('bike_free_training_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('record_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('path_id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bike_free_training_records_record_id'), 'bike_free_training_records', ['record_id'], unique=True)

    op.create_table('country_grid_cells',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('country_code', sa.String(), nullable=False),
    sa.Column('grid_code', sa.String(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_code', 'grid_code', name='uq_country_grid_cells_country_code_grid_code')
    )
    op.create_index('idx_country_grid_cells_geom', 'country_grid_cells', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_country_grid_cells_country_code'), 'country_grid_cells', ['country_code'], unique=False)

    op.create_table('running_free_training_paths',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('path_id', sa.String(), nullable=False),
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('path', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_running_free_training_paths_path_id'), 'running_free_training_paths', ['path_id'], unique=True)
    op.create_table('running_free_training_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('record_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('path_id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_running_free_training_records_record_id'), 'running_free_training_records', ['record_id'], unique=True)

    op.create_table('user_grid_familiarity_bike',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('season_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('grid_id', sa.UUID(), nullable=False),
    sa.Column('familiarity_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id', 'user_id', 'grid_id', name='uq_season_user_grid_familiarity_bike')
    )
    op.create_index(op.f('ix_user_grid_familiarity_bike_grid_id'), 'user_grid_familiarity_bike', ['grid_id'], unique=False)
    op.create_index(op.f('ix_user_grid_familiarity_bike_season_id'), 'user_grid_familiarity_bike', ['season_id'], unique=False)
    op.create_index(op.f('ix_user_grid_familiarity_bike_user_id'), 'user_grid_familiarity_bike', ['user_id'], unique=False)

    op.create_table('user_grid_familiarity_running',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('season_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('grid_id', sa.UUID(), nullable=False),
    sa.Column('familiarity_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id', 'user_id', 'grid_id', name='uq_season_user_grid_familiarity_running')
    )
    op.create_index(op.f('ix_user_grid_familiarity_running_grid_id'), 'user_grid_familiarity_running', ['grid_id'], unique=False)
    op.create_index(op.f('ix_user_grid_familiarity_running_season_id'), 'user_grid_familiarity_running', ['season_id'], unique=False)
    op.create_index(op.f('ix_user_grid_familiarity_running_user_id'), 'user_grid_familiarity_running', ['user_id'], unique=False)

    op.add_column(
        'bike_career_scores',
        sa.Column('xp', sa.Integer(), nullable=True, server_default='0')
    )
    op.execute("UPDATE bike_career_scores SET xp = 0 WHERE xp IS NULL")
    op.alter_column('bike_career_scores', 'xp', nullable=False, server_default=None)

    op.add_column(
        'running_career_scores',
        sa.Column('xp', sa.Integer(), nullable=True, server_default='0')
    )
    op.execute("UPDATE running_career_scores SET xp = 0 WHERE xp IS NULL")
    op.alter_column('running_career_scores', 'xp', nullable=False, server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # skip
    # ### end Alembic commands ###
