"""enable_lod_grids_system

Revision ID: 8c976e67ae77
Revises: ee6a7cd5d2eb
Create Date: 2026-04-03 18:05:01.628115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c976e67ae77'
down_revision: Union[str, None] = 'ee6a7cd5d2eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_grid_familiarity_bike_agg',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('season_id', sa.UUID(), nullable=False),
    sa.Column('country_code', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('grid_x', sa.Integer(), nullable=False),
    sa.Column('grid_y', sa.Integer(), nullable=False),
    sa.Column('familiarity_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id', 'user_id', 'country_code', 'level', 'grid_x', 'grid_y', name='uq_user_grid_familiarity_bike_agg_season_user_country_grid')
    )
    op.create_index(op.f('ix_user_grid_familiarity_bike_agg_country_code'), 'user_grid_familiarity_bike_agg', ['country_code'], unique=False)
    op.create_index(op.f('ix_user_grid_familiarity_bike_agg_season_id'), 'user_grid_familiarity_bike_agg', ['season_id'], unique=False)
    op.create_index(op.f('ix_user_grid_familiarity_bike_agg_user_id'), 'user_grid_familiarity_bike_agg', ['user_id'], unique=False)

    op.create_table('user_grid_familiarity_running_agg',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('season_id', sa.UUID(), nullable=False),
    sa.Column('country_code', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('grid_x', sa.Integer(), nullable=False),
    sa.Column('grid_y', sa.Integer(), nullable=False),
    sa.Column('familiarity_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id', 'user_id', 'country_code', 'level', 'grid_x', 'grid_y', name='uq_user_grid_familiarity_running_agg_season_user_country_grid')
    )
    op.create_index(op.f('ix_user_grid_familiarity_running_agg_country_code'), 'user_grid_familiarity_running_agg', ['country_code'], unique=False)
    op.create_index(op.f('ix_user_grid_familiarity_running_agg_season_id'), 'user_grid_familiarity_running_agg', ['season_id'], unique=False)
    op.create_index(op.f('ix_user_grid_familiarity_running_agg_user_id'), 'user_grid_familiarity_running_agg', ['user_id'], unique=False)

    op.add_column('country_grid_cells', sa.Column('grid_x', sa.Integer(), nullable=True))
    op.add_column('country_grid_cells', sa.Column('grid_y', sa.Integer(), nullable=True))
    op.execute("""
    UPDATE country_grid_cells
    SET
        grid_x = split_part(grid_code, '_', 2)::int,
        grid_y = split_part(grid_code, '_', 3)::int
    """)
    op.alter_column('country_grid_cells', 'grid_x', nullable=False)
    op.alter_column('country_grid_cells', 'grid_y', nullable=False)
    op.create_unique_constraint('uq_country_grid_cells_country_code_gridx_gridy', 'country_grid_cells', ['country_code', 'grid_x', 'grid_y'])

    op.drop_constraint(op.f('uq_country_grid_cells_country_code_grid_code'), 'country_grid_cells', type_='unique')
    op.drop_column('country_grid_cells', 'grid_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # skip downgrade
    # ### end Alembic commands ###
