"""optimize tracks table

Revision ID: 8f526669af0e
Revises: ef36cc82d9d3
Create Date: 2025-06-12 04:03:58.728185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f526669af0e'
down_revision: Union[str, None] = 'ef36cc82d9d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('start_date', sa.DateTime(timezone=True), nullable=False))
    op.add_column('tracks', sa.Column('end_date', sa.DateTime(timezone=True), nullable=False))
    op.add_column('tracks', sa.Column('sub_region_name', sa.String(), nullable=False))
    op.drop_column('tracks', 'total_participants')
    op.drop_column('tracks', 'current_participants')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('current_participants', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tracks', sa.Column('total_participants', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('tracks', 'sub_region_name')
    op.drop_column('tracks', 'end_date')
    op.drop_column('tracks', 'start_date')
    # ### end Alembic commands ###
