"""add gender to career_scores table

Revision ID: 92323a3e18ee
Revises: bbca7be114c3
Create Date: 2025-09-22 04:40:46.595737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '92323a3e18ee'
down_revision: Union[str, None] = 'bbca7be114c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bike_career_scores', sa.Column('gender', postgresql.ENUM('male', 'female', name='gender', create_type=False), nullable=True))
    op.execute("UPDATE bike_career_scores SET gender = 'male'::gender")
    op.alter_column('bike_career_scores', 'gender', nullable=False)
    op.add_column('running_career_scores', sa.Column('gender', postgresql.ENUM('male', 'female', name='gender', create_type=False), nullable=True))
    op.execute("UPDATE running_career_scores SET gender = 'male'::gender")
    op.alter_column('running_career_scores', 'gender', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('running_career_scores', 'gender')
    op.drop_column('bike_career_scores', 'gender')
    # ### end Alembic commands ###
