"""opt training records

Revision ID: 9237af18ace5
Revises: 861e5fec3205
Create Date: 2026-03-10 11:12:32.531558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9237af18ace5'
down_revision: Union[str, None] = '861e5fec3205'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bike_free_training_paths', 'record_id')
    op.drop_index(op.f('ix_bike_free_training_records_local_date'), table_name='bike_free_training_records')
    op.create_index('idx_bike_free_training_records_user_date', 'bike_free_training_records', ['user_id', 'local_date'], unique=False)
    op.drop_column('running_free_training_paths', 'record_id')
    op.drop_index(op.f('ix_running_free_training_records_local_date'), table_name='running_free_training_records')
    op.create_index('idx_running_free_training_records_user_date', 'running_free_training_records', ['user_id', 'local_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
