"""add season_id to seasons table

Revision ID: 932cbfc2b831
Revises: f3e5df2593f7
Create Date: 2025-06-05 02:23:54.326089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '932cbfc2b831'
down_revision: Union[str, None] = 'f3e5df2593f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('event_id', sa.String(), nullable=False))
    op.drop_index('ix_events_public_id', table_name='events')
    op.create_index(op.f('ix_events_event_id'), 'events', ['event_id'], unique=True)
    op.drop_column('events', 'public_id')
    
    op.add_column('seasons', sa.Column('season_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_seasons_season_id'), 'seasons', ['season_id'], unique=True)
    op.execute("UPDATE seasons SET season_id = 'season_12345678' WHERE name = 'x0赛季'")
    op.execute("UPDATE seasons SET season_id = 'season_87654321' WHERE name = 'x1赛季'")
    op.alter_column('seasons', 'season_id', nullable=False)

    op.add_column('tracks', sa.Column('track_id', sa.String(), nullable=False))
    op.drop_index('ix_tracks_public_id', table_name='tracks')
    op.create_index(op.f('ix_tracks_track_id'), 'tracks', ['track_id'], unique=True)
    op.drop_column('tracks', 'public_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('public_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_tracks_track_id'), table_name='tracks')
    op.create_index('ix_tracks_public_id', 'tracks', ['public_id'], unique=True)
    op.drop_column('tracks', 'track_id')
    op.drop_index(op.f('ix_seasons_season_id'), table_name='seasons')
    op.drop_column('seasons', 'season_id')
    op.add_column('events', sa.Column('public_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_events_event_id'), table_name='events')
    op.create_index('ix_events_public_id', 'events', ['public_id'], unique=True)
    op.drop_column('events', 'event_id')
    # ### end Alembic commands ###
