"""change role from string to enum

Revision ID: 939bdc24aaa9
Revises: 6cb93d218e07
Create Date: 2025-10-02 01:04:28.541020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '939bdc24aaa9'
down_revision: Union[str, None] = '6cb93d218e07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    userrole_enum = postgresql.ENUM('user', 'admin', name='userrole')
    userrole_enum.create(op.get_bind(), checkfirst=True)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('user', 'admin', name='userrole'),
               existing_nullable=False, postgresql_using="role::userrole")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('user', 'admin', name='userrole'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
