"""enable i18n in competition & asset tables

Revision ID: 93cc2f3bf5ac
Revises: 84b1b4f080b6
Create Date: 2026-01-11 15:44:40.111342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '93cc2f3bf5ac'
down_revision: Union[str, None] = '84b1b4f080b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bike_events', sa.Column('name_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('bike_events', sa.Column('description_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.execute(
        """
        UPDATE bike_events
        SET
            name_i18n = jsonb_build_object('zh-Hans', name),
            description_i18n = CASE
                WHEN description IS NOT NULL
                THEN jsonb_build_object('zh-Hans', description)
                ELSE NULL
            END
        WHERE name_i18n IS NULL;
        """
    )
    op.drop_column('bike_events', 'name')
    op.drop_column('bike_events', 'description')
    op.alter_column("bike_events", "name_i18n", nullable=False)

    op.add_column('bike_seasons', sa.Column('name_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.execute(
        """
        UPDATE bike_seasons
        SET name_i18n = jsonb_build_object('zh-Hans', name)
        WHERE name_i18n IS NULL;
        """
    )
    op.drop_column('bike_seasons', 'name')
    op.alter_column("bike_seasons", "name_i18n", nullable=False)

    op.drop_index(op.f('ix_bike_teams_team_code'), table_name='bike_teams')
    op.create_index('uq_bike_teams_teamcode_status', 'bike_teams', ['team_code'], unique=True, postgresql_where=sa.text("status IN ('prepared', 'locked', 'ready', 'recording')"))

    op.add_column('bike_tracks', sa.Column('name_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('bike_tracks', sa.Column('sub_region_name_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.execute(
        """
        UPDATE bike_tracks
        SET
            name_i18n = jsonb_build_object('zh-Hans', name),
            sub_region_name_i18n = jsonb_build_object('zh-Hans', sub_region_name)
        WHERE name_i18n IS NULL;
        """
    )
    op.drop_column('bike_tracks', 'sub_region_name')
    op.drop_column('bike_tracks', 'name')
    op.alter_column("bike_tracks", "name_i18n", nullable=False)
    op.alter_column("bike_tracks", "sub_region_name_i18n", nullable=False)

    op.add_column('cp_asset_defs', sa.Column('name_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('cp_asset_defs', sa.Column('description_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.execute(
        """
        UPDATE cp_asset_defs
        SET
            name_i18n = jsonb_build_object('zh-Hans', name),
            description_i18n = jsonb_build_object('zh-Hans', description)
        WHERE name_i18n IS NULL;
        """
    )
    op.drop_column('cp_asset_defs', 'name')
    op.drop_column('cp_asset_defs', 'description')
    op.alter_column("cp_asset_defs", "name_i18n", nullable=False)
    op.alter_column("cp_asset_defs", "description_i18n", nullable=False)

    op.add_column('equipment_card_defs', sa.Column('name_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('equipment_card_defs', sa.Column('description_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('equipment_card_defs', sa.Column('skill1_description_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('equipment_card_defs', sa.Column('skill2_description_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('equipment_card_defs', sa.Column('skill3_description_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.execute(
        """
        UPDATE equipment_card_defs
        SET
            name_i18n = jsonb_build_object('zh-Hans', name),
            description_i18n = jsonb_build_object('zh-Hans', description),
            skill1_description_i18n = CASE
                WHEN skill1_description IS NOT NULL
                THEN jsonb_build_object('zh-Hans', skill1_description)
                ELSE NULL
            END,
            skill2_description_i18n = CASE
                WHEN skill2_description IS NOT NULL
                THEN jsonb_build_object('zh-Hans', skill2_description)
                ELSE NULL
            END,
            skill3_description_i18n = CASE
                WHEN skill3_description IS NOT NULL
                THEN jsonb_build_object('zh-Hans', skill3_description)
                ELSE NULL
            END
        WHERE name_i18n IS NULL;
        """
    )
    op.drop_column('equipment_card_defs', 'description')
    op.drop_column('equipment_card_defs', 'skill3_description')
    op.drop_column('equipment_card_defs', 'skill2_description')
    op.drop_column('equipment_card_defs', 'skill1_description')
    op.drop_column('equipment_card_defs', 'name')
    op.alter_column("equipment_card_defs", "name_i18n", nullable=False)
    op.alter_column("equipment_card_defs", "description_i18n", nullable=False)

    op.add_column('running_events', sa.Column('name_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('running_events', sa.Column('description_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.execute(
        """
        UPDATE running_events
        SET
            name_i18n = jsonb_build_object('zh-Hans', name),
            description_i18n = CASE
                WHEN description IS NOT NULL
                THEN jsonb_build_object('zh-Hans', description)
                ELSE NULL
            END
        WHERE name_i18n IS NULL;
        """
    )
    op.drop_column('running_events', 'name')
    op.drop_column('running_events', 'description')
    op.alter_column("running_events", "name_i18n", nullable=False)

    op.add_column('running_seasons', sa.Column('name_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.execute(
        """
        UPDATE running_seasons
        SET name_i18n = jsonb_build_object('zh-Hans', name)
        WHERE name_i18n IS NULL;
        """
    )
    op.drop_column('running_seasons', 'name')
    op.alter_column("running_seasons", "name_i18n", nullable=False)

    op.drop_index(op.f('ix_running_teams_team_code'), table_name='running_teams')
    op.create_index('uq_running_teams_teamcode_status', 'running_teams', ['team_code'], unique=True, postgresql_where=sa.text("status IN ('prepared', 'locked', 'ready', 'recording')"))

    op.add_column('running_tracks', sa.Column('name_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('running_tracks', sa.Column('sub_region_name_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.execute(
        """
        UPDATE running_tracks
        SET
            name_i18n = jsonb_build_object('zh-Hans', name),
            sub_region_name_i18n = jsonb_build_object('zh-Hans', sub_region_name)
        WHERE name_i18n IS NULL;
        """
    )
    op.drop_column('running_tracks', 'sub_region_name')
    op.drop_column('running_tracks', 'name')
    op.alter_column("running_tracks", "name_i18n", nullable=False)
    op.alter_column("running_tracks", "sub_region_name_i18n", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    raise NotImplementedError("i18n migration is irreversible")
    # ### end Alembic commands ###
