"""vategorize events & tracks table by sport type

Revision ID: a79f612c0ccf
Revises: 3ba2d7b953ed
Create Date: 2025-06-16 01:25:07.013082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a79f612c0ccf'
down_revision: Union[str, None] = '3ba2d7b953ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bike_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('region_id', sa.UUID(), nullable=False),
    sa.Column('season_id', sa.UUID(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bike_events_event_id'), 'bike_events', ['event_id'], unique=True)
    op.create_table('running_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('region_id', sa.UUID(), nullable=False),
    sa.Column('season_id', sa.UUID(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_running_events_event_id'), 'running_events', ['event_id'], unique=True)
    op.create_table('bike_tracks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('track_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('from_lat', sa.Float(), nullable=False),
    sa.Column('from_lng', sa.Float(), nullable=False),
    sa.Column('to_lat', sa.Float(), nullable=False),
    sa.Column('to_lng', sa.Float(), nullable=False),
    sa.Column('elevation_difference', sa.Integer(), nullable=True),
    sa.Column('sub_region_name', sa.String(), nullable=False),
    sa.Column('fee', sa.Integer(), nullable=True),
    sa.Column('prize_pool', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['bike_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bike_tracks_track_id'), 'bike_tracks', ['track_id'], unique=True)
    op.create_table('running_tracks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('track_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('from_lat', sa.Float(), nullable=False),
    sa.Column('from_lng', sa.Float(), nullable=False),
    sa.Column('to_lat', sa.Float(), nullable=False),
    sa.Column('to_lng', sa.Float(), nullable=False),
    sa.Column('elevation_difference', sa.Integer(), nullable=True),
    sa.Column('sub_region_name', sa.String(), nullable=False),
    sa.Column('fee', sa.Integer(), nullable=True),
    sa.Column('prize_pool', sa.Integer(), nullable=True),
    sa.Column('distance', sa.Float(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['running_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_running_tracks_track_id'), 'running_tracks', ['track_id'], unique=True)
    op.create_table('bike_race_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('track_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_team', sa.Boolean(), nullable=True),
    sa.Column('team_code', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['bike_tracks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('race_records')
    op.drop_index('ix_tracks_track_id', table_name='tracks')
    op.drop_table('tracks')
    op.drop_index('ix_events_event_id', table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('start_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('end_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('region_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('season_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name='events_region_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], name='events_season_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='events_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_events_event_id', 'events', ['event_id'], unique=True)
    op.create_table('race_records',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('track_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('season_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('duration_seconds', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('start_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('end_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_team', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('team_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name='race_records_event_id_fkey'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], name='race_records_season_id_fkey'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], name='race_records_track_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='race_records_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='race_records_pkey')
    )
    op.create_table('tracks',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('from_lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('from_lng', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('to_lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('to_lng', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('elevation_difference', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fee', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('prize_pool', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('track_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('start_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('end_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('sub_region_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name='tracks_event_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='tracks_pkey')
    )
    op.create_index('ix_tracks_track_id', 'tracks', ['track_id'], unique=True)
    op.drop_table('bike_race_records')
    op.drop_index(op.f('ix_running_tracks_track_id'), table_name='running_tracks')
    op.drop_table('running_tracks')
    op.drop_index(op.f('ix_bike_tracks_track_id'), table_name='bike_tracks')
    op.drop_table('bike_tracks')
    op.drop_index(op.f('ix_running_events_event_id'), table_name='running_events')
    op.drop_table('running_events')
    op.drop_index(op.f('ix_bike_events_event_id'), table_name='bike_events')
    op.drop_table('bike_events')
    # ### end Alembic commands ###
