"""add_des_to_buff_grids_table

Revision ID: acb543ae65eb
Revises: 515edde6efe1
Create Date: 2026-05-13 19:08:21.957056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'acb543ae65eb'
down_revision: Union[str, None] = '515edde6efe1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bike_effect_grids', sa.Column('description_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('running_effect_grids', sa.Column('description_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
