"""enable i18n in announcement table

Revision ID: ae560309c411
Revises: 21db316dd537
Create Date: 2025-12-17 01:44:28.277497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae560309c411'
down_revision: Union[str, None] = '21db316dd537'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('announcements', 'content')

    op.add_column('announcements', sa.Column('content_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.execute("UPDATE announcements SET content_i18n = '{}' WHERE content_i18n IS NULL")
    op.alter_column('announcements', 'content_i18n', nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcements', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('announcements', 'content_i18n')
    # ### end Alembic commands ###
