"""add equip_card_transactions table

Revision ID: b36028c377a1
Revises: 24b5aa2a9a40
Create Date: 2025-08-27 03:46:16.906494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b36028c377a1'
down_revision: Union[str, None] = '24b5aa2a9a40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE assetoperation ADD VALUE IF NOT EXISTS 'DESTROY'")
    op.execute("ALTER TYPE assetoperation ADD VALUE IF NOT EXISTS 'UPGRADE'")

    op.create_table('equip_card_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('operation', postgresql.ENUM(name='assetoperation', create_type=False), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('equip_card_transactions')
    # ### end Alembic commands ###
