"""add method to user_realname_identities table

Revision ID: b4e457342c8d
Revises: 826f74cd155f
Create Date: 2026-03-18 01:05:12.526969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'b4e457342c8d'
down_revision: Union[str, None] = '826f74cd155f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    realnamemethod = sa.Enum(
        'idcard', 'passport', 'drivingLicense',
       name='realnamemethod'
    )
    realnamemethod.create(op.get_bind(), checkfirst=True)

    op.add_column('user_realname_identities', sa.Column('method', postgresql.ENUM('idcard', 'passport', 'drivingLicense', name='realnamemethod', create_type=False), nullable=True))
    op.execute("""
        UPDATE user_realname_identities
        SET method = 'idcard'
    """)
    op.alter_column('user_realname_identities', 'method', nullable=False)

    op.execute("""
        UPDATE user_realname_identities
        SET card_id_hash = gen_random_uuid()::text
        WHERE card_id_hash IS NULL
    """)
    op.alter_column('user_realname_identities', 'card_id_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('uq_user_realname_identities_card_id_hash'), 'user_realname_identities', type_='unique')
    op.create_unique_constraint('uq_user_realname_identities_country_method_card', 'user_realname_identities', ['country_code', 'method', 'card_id_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
