"""optimize enum teamstatus

Revision ID: b82d3c5800e8
Revises: 9f51c28eabad
Create Date: 2025-07-22 07:34:34.677679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b82d3c5800e8'
down_revision: Union[str, None] = '9f51c28eabad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bike_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('bike_race_records', 'status',
               existing_type=postgresql.ENUM('notStarted', 'recording', 'completed', name='recordstatus'),
               nullable=False)
    op.alter_column('bike_race_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('bike_seasons', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('bike_team_applied_members', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('bike_team_members', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('bike_teams', 'members_count_max',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bike_teams', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('bike_teams', 'is_locked',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('bike_teams', 'status',
               existing_type=postgresql.ENUM('prepared', 'ready', 'recording', name='teamstatus'),
               nullable=False)
    op.alter_column('bike_teams', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('bike_tracks', 'elevation_difference',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bike_tracks', 'prize_pool',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bike_tracks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('ccasset_transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('cpasset_price', 'is_on_shelves',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('cpasset_transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('regions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('running_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('running_race_records', 'status',
               existing_type=postgresql.ENUM('notStarted', 'recording', 'completed', name='recordstatus'),
               nullable=False)
    op.alter_column('running_race_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('running_seasons', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('running_tracks', 'elevation_difference',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('running_tracks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_ccassets', 'balance',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_ccassets', 'can_recharge',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('user_ccassets', 'can_withdraw',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('user_ccassets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_cpassets', 'balance',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_cpassets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_equipment_cards', 'level',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_equipment_cards', 'lucky_value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('user_equipment_cards', 'income_multiple',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('user_equipment_cards', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_follows', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_realname_auth',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'is_identity_auth',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'is_display_gender',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'is_display_age',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'is_display_location',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'enable_auto_location',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'is_display_identity',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.execute("ALTER TYPE teamstatus ADD VALUE IF NOT EXISTS 'locked'")
    op.execute("ALTER TYPE teamstatus ADD VALUE IF NOT EXISTS 'completed'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_display_identity',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'enable_auto_location',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_display_location',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_display_age',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_display_gender',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_identity_auth',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_realname_auth',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user_follows', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_equipment_cards', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_equipment_cards', 'income_multiple',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('user_equipment_cards', 'lucky_value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('user_equipment_cards', 'level',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_cpassets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_cpassets', 'balance',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_ccassets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_ccassets', 'can_withdraw',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user_ccassets', 'can_recharge',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user_ccassets', 'balance',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('running_tracks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('running_tracks', 'elevation_difference',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('running_seasons', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('running_race_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('running_race_records', 'status',
               existing_type=postgresql.ENUM('notStarted', 'recording', 'completed', name='recordstatus'),
               nullable=True)
    op.alter_column('running_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('regions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('cpasset_transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('cpasset_price', 'is_on_shelves',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('ccasset_transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('bike_tracks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('bike_tracks', 'prize_pool',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bike_tracks', 'elevation_difference',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bike_teams', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('bike_teams', 'status',
               existing_type=postgresql.ENUM('prepared', 'ready', 'recording', name='teamstatus'),
               nullable=True)
    op.alter_column('bike_teams', 'is_locked',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('bike_teams', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('bike_teams', 'members_count_max',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bike_team_members', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('bike_team_applied_members', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('bike_seasons', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('bike_race_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('bike_race_records', 'status',
               existing_type=postgresql.ENUM('notStarted', 'recording', 'completed', name='recordstatus'),
               nullable=True)
    op.alter_column('bike_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
