"""add email to users table

Revision ID: b915c9e26818
Revises: 9f6f87d67068
Create Date: 2025-12-29 06:28:05.245588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b915c9e26818'
down_revision: Union[str, None] = '9f6f87d67068'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    op.create_index('uq_users_apple_id_status', 'users', ['apple_id'], unique=True, postgresql_where=sa.text("status IN ('normal', 'banned')"))
    op.create_index('uq_users_email_status', 'users', ['email'], unique=True, postgresql_where=sa.text("status IN ('normal', 'banned')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_users_email_status', table_name='users', postgresql_where=sa.text("status IN ('normal', 'banned')"))
    op.drop_index('uq_users_apple_id_status', table_name='users', postgresql_where=sa.text("status IN ('normal', 'banned')"))
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
