"""add region_grid_cells table & add grid_count to regions table

Revision ID: bae842227238
Revises: 9237af18ace5
Create Date: 2026-03-12 16:37:10.275446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bae842227238'
down_revision: Union[str, None] = '9237af18ace5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('region_grid_cells',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('region_id', sa.UUID(), nullable=False),
    sa.Column('grid_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region_id', 'grid_id', name='uq_region_grid_cells_region_grid')
    )
    op.create_index(op.f('ix_region_grid_cells_grid_id'), 'region_grid_cells', ['grid_id'], unique=False)
    op.create_index(op.f('ix_region_grid_cells_region_id'), 'region_grid_cells', ['region_id'], unique=False)

    op.execute("INSERT INTO region_grid_cells(id, region_id, grid_id) SELECT gen_random_uuid(), r.id, g.id FROM regions r JOIN country_grid_cells g ON ST_Intersects(r.boundary, g.geom)")

    op.add_column('regions', sa.Column('grid_count', sa.Integer(), nullable=True, server_default='0'))
    op.execute("UPDATE regions SET grid_count = (SELECT COUNT(*) FROM region_grid_cells rg WHERE rg.region_id = regions.id)")
    op.alter_column('regions', 'grid_count', nullable=False, server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
