"""change reward type to jsonb in leaderboard table

Revision ID: bbca7be114c3
Revises: 4073f0cae353
Create Date: 2025-09-19 06:45:59.221707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bbca7be114c3'
down_revision: Union[str, None] = '4073f0cae353'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bike_leaderboard', 'reward',
               existing_type=sa.INTEGER(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               postgresql_using='to_jsonb(reward)'
               )
    op.alter_column('running_leaderboard', 'reward',
               existing_type=sa.INTEGER(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               postgresql_using='to_jsonb(reward)'
               )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('running_leaderboard', 'reward',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('bike_leaderboard', 'reward',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
