"""add bonus_by_team_members table

Revision ID: bcf518f08ce3
Revises: 3abbca4dd41b
Create Date: 2025-11-18 00:02:23.676356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcf518f08ce3'
down_revision: Union[str, None] = '3abbca4dd41b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bike_bonus_by_team_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('bonus_in_ratio', sa.Float(), nullable=True),
    sa.Column('bonus_in_seconds', sa.Float(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'team_id', name='uq_bike_bonus_by_team_members_user_team')
    )
    op.create_index(op.f('ix_bike_bonus_by_team_members_team_id'), 'bike_bonus_by_team_members', ['team_id'], unique=False)
    op.create_index(op.f('ix_bike_bonus_by_team_members_user_id'), 'bike_bonus_by_team_members', ['user_id'], unique=False)
    op.create_table('running_bonus_by_team_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('bonus_in_ratio', sa.Float(), nullable=True),
    sa.Column('bonus_in_seconds', sa.Float(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'team_id', name='uq_running_bonus_by_team_members_user_team')
    )
    op.create_index(op.f('ix_running_bonus_by_team_members_team_id'), 'running_bonus_by_team_members', ['team_id'], unique=False)
    op.create_index(op.f('ix_running_bonus_by_team_members_user_id'), 'running_bonus_by_team_members', ['user_id'], unique=False)
    op.add_column('bike_race_records', sa.Column('is_finish_bonus_computing', sa.Boolean(), nullable=True))
    op.add_column('running_race_records', sa.Column('is_finish_bonus_computing', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('running_race_records', 'is_finish_bonus_computing')
    op.drop_column('bike_race_records', 'is_finish_bonus_computing')
    op.drop_index(op.f('ix_running_bonus_by_team_members_user_id'), table_name='running_bonus_by_team_members')
    op.drop_index(op.f('ix_running_bonus_by_team_members_team_id'), table_name='running_bonus_by_team_members')
    op.drop_table('running_bonus_by_team_members')
    op.drop_index(op.f('ix_bike_bonus_by_team_members_user_id'), table_name='bike_bonus_by_team_members')
    op.drop_index(op.f('ix_bike_bonus_by_team_members_team_id'), table_name='bike_bonus_by_team_members')
    op.drop_table('bike_bonus_by_team_members')
    # ### end Alembic commands ###
