"""add product_id & delete env in user_subscriptions table

Revision ID: bfe130e79547
Revises: 6cd242d2e002
Create Date: 2025-12-04 15:10:55.481217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfe130e79547'
down_revision: Union[str, None] = '6cd242d2e002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_subscriptions', sa.Column('product_id', sa.String(), nullable=True))
    op.drop_index('ix_user_subscriptions_apple_latest_transaction_id', table_name='user_subscriptions')
    op.drop_index('ix_user_subscriptions_apple_original_transaction_id', table_name='user_subscriptions')
    op.drop_column('user_subscriptions', 'apple_environment')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_subscriptions', sa.Column('apple_environment', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_user_subscriptions_apple_original_transaction_id', 'user_subscriptions', ['apple_original_transaction_id'], unique=False)
    op.create_index('ix_user_subscriptions_apple_latest_transaction_id', 'user_subscriptions', ['apple_latest_transaction_id'], unique=False)
    op.drop_column('user_subscriptions', 'product_id')
    # ### end Alembic commands ###
