"""enable apple login & realname auth

Revision ID: c28e211d0ea3
Revises: d534164f559a
Create Date: 2025-10-01 00:07:22.132630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c28e211d0ea3'
down_revision: Union[str, None] = 'd534164f559a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_real_name',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name_Cn', sa.String(), nullable=True),
    sa.Column('name_En', sa.String(), nullable=False),
    sa.Column('birth_date', sa.String(), nullable=False),
    sa.Column('card_id', sa.String(), nullable=False),
    sa.Column('name_code', sa.String(), nullable=True),
    sa.Column('issued_code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('apple_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('apple_email', sa.String(), nullable=True))
    op.drop_index('ix_users_phone_number', table_name='users')
    op.drop_constraint('users_nickname_key', 'users', type_='unique')
    op.create_index('uq_users_nickname_status', 'users', ['nickname'], unique=True, postgresql_where=sa.text("status IN ('normal', 'banned')"))
    op.create_index('uq_users_phone_status', 'users', ['phone_number'], unique=True, postgresql_where=sa.text("status IN ('normal', 'banned')"))
    op.drop_column('users', 'is_realname_auth')
    op.drop_column('users', 'is_identity_auth')
    op.drop_column('users', 'birthday')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('birthday', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_identity_auth', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('is_realname_auth', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_index('uq_users_phone_status', table_name='users', postgresql_where=sa.text("status IN ('normal', 'banned')"))
    op.drop_index('uq_users_nickname_status', table_name='users', postgresql_where=sa.text("status IN ('normal', 'banned')"))
    op.create_unique_constraint('users_nickname_key', 'users', ['nickname'])
    op.create_index('ix_users_phone_number', 'users', ['phone_number'], unique=True)
    op.drop_column('users', 'apple_email')
    op.drop_column('users', 'apple_id')
    op.drop_table('user_real_name')
    # ### end Alembic commands ###
