"""enable i18n in bannerads table

Revision ID: c8e601be0a82
Revises: 836c94b04e1a
Create Date: 2026-01-17 03:37:26.464515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c8e601be0a82'
down_revision: Union[str, None] = '836c94b04e1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banner_ads', sa.Column('image_url_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.execute(
        """
        UPDATE banner_ads
        SET
            image_url_i18n = jsonb_build_object('zh-Hans', image_url)
        WHERE image_url_i18n IS NULL;
        """
    )
    op.drop_column('banner_ads', 'image_url')
    op.alter_column("banner_ads", "image_url_i18n", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banner_ads', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('banner_ads', 'image_url_i18n')
    # ### end Alembic commands ###
