"""delete SubscriptionStatus enum

Revision ID: cb7906842dae
Revises: d39d3ccfe350
Create Date: 2025-11-01 05:57:11.101374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb7906842dae'
down_revision: Union[str, None] = 'd39d3ccfe350'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. 先添加 is_active 列为可空
    op.add_column('user_subscriptions', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.execute("UPDATE user_subscriptions SET is_active = (status = 'active') WHERE status IS NOT NULL")
    op.alter_column(
        'user_subscriptions',
        'is_active',
        existing_type=sa.Boolean(),
        nullable=False
    )
    op.drop_column('user_subscriptions', 'status')
    op.execute("DROP TYPE IF EXISTS subscriptionstatus")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_subscriptions', sa.Column('status', postgresql.ENUM('active', 'inactive', name='subscriptionstatus'), autoincrement=False, nullable=False))
    op.drop_column('user_subscriptions', 'is_active')
    # ### end Alembic commands ###
