"""separate user_settings table from users

Revision ID: cc57762de91c
Revises: 7bbe44da2748
Create Date: 2025-10-01 17:30:06.780888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc57762de91c'
down_revision: Union[str, None] = '7bbe44da2748'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_real_name_hk',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('gender', postgresql.ENUM('male', 'female', name='gender', create_type=False), nullable=False),
    sa.Column('birth_date', sa.String(), nullable=False),
    sa.Column('name_Cn', sa.String(), nullable=True),
    sa.Column('name_En', sa.String(), nullable=False),
    sa.Column('card_id', sa.String(), nullable=False),
    sa.Column('name_code', sa.String(), nullable=True),
    sa.Column('issued_code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('is_display_gender', sa.Boolean(), nullable=False),
    sa.Column('is_display_age', sa.Boolean(), nullable=False),
    sa.Column('is_display_location', sa.Boolean(), nullable=False),
    sa.Column('enable_auto_location', sa.Boolean(), nullable=False),
    sa.Column('is_display_identity', sa.Boolean(), nullable=False),
    sa.Column('default_sport', postgresql.ENUM('running', 'bike', name='sporttype', create_type=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_real_name')
    op.drop_column('users', 'birthday')
    op.drop_column('users', 'is_display_identity')
    op.drop_column('users', 'is_display_age')
    op.drop_column('users', 'is_display_location')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'default_sport')
    op.drop_column('users', 'is_display_gender')
    op.drop_column('users', 'enable_auto_location')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('enable_auto_location', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('is_display_gender', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('default_sport', postgresql.ENUM('running', 'bike', name='sporttype'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('gender', postgresql.ENUM('male', 'female', name='gender'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_display_location', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('is_display_age', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('is_display_identity', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('birthday', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_table('user_real_name',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name_Cn', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name_En', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('card_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('issued_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_real_name_pkey')
    )
    op.drop_table('user_settings')
    op.drop_table('user_real_name_hk')
    # ### end Alembic commands ###
