"""add subscription tables

Revision ID: d39d3ccfe350
Revises: ef4279d7e35a
Create Date: 2025-11-01 01:49:25.207928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd39d3ccfe350'
down_revision: Union[str, None] = 'ef4279d7e35a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    subscriptioneventtype_enum = postgresql.ENUM('rewarded', 'created', 'renewed', 'refunded', 'auto_renew_off', 'auto_renew_on', 'grace_started', 'grace_ended', name='subscriptioneventtype')
    subscriptioneventtype_enum.create(op.get_bind(), checkfirst=True)
    subscriptionperiod_enum = postgresql.ENUM('monthly', 'quarterly', 'yearly', name='subscriptionperiod')
    subscriptionperiod_enum.create(op.get_bind(), checkfirst=True)
    subscriptionstatus_enum = postgresql.ENUM('active', 'inactive', name='subscriptionstatus')
    subscriptionstatus_enum.create(op.get_bind(), checkfirst=True)

    op.create_table('subscription_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('event_type', postgresql.ENUM('rewarded', 'created', 'renewed', 'refunded', 'auto_renew_off', 'auto_renew_on', 'grace_started', 'grace_ended', name='subscriptioneventtype', create_type=False), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_events_subscription_id'), 'subscription_events', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_subscription_events_user_id'), 'subscription_events', ['user_id'], unique=False)
    op.create_table('subscription_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('period', postgresql.ENUM('monthly', 'quarterly', 'yearly', name='subscriptionperiod', create_type=False), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('apple_product_id', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('apple_product_id'),
    sa.UniqueConstraint('plan_code')
    )
    op.create_table('user_subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', postgresql.ENUM('active', 'inactive', name='subscriptionstatus', create_type=False), nullable=False),
    sa.Column('auto_renew', sa.Boolean(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('grace_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('apple_original_transaction_id', sa.String(), nullable=True),
    sa.Column('apple_latest_transaction_id', sa.String(), nullable=True),
    sa.Column('apple_environment', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_subscriptions_apple_latest_transaction_id'), 'user_subscriptions', ['apple_latest_transaction_id'], unique=False)
    op.create_index(op.f('ix_user_subscriptions_apple_original_transaction_id'), 'user_subscriptions', ['apple_original_transaction_id'], unique=False)
    op.create_index(op.f('ix_user_subscriptions_user_id'), 'user_subscriptions', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_subscriptions_user_id'), table_name='user_subscriptions')
    op.drop_index(op.f('ix_user_subscriptions_apple_original_transaction_id'), table_name='user_subscriptions')
    op.drop_index(op.f('ix_user_subscriptions_apple_latest_transaction_id'), table_name='user_subscriptions')
    op.drop_table('user_subscriptions')
    op.drop_table('subscription_plans')
    op.drop_index(op.f('ix_subscription_events_user_id'), table_name='subscription_events')
    op.drop_index(op.f('ix_subscription_events_subscription_id'), table_name='subscription_events')
    op.drop_table('subscription_events')
    # ### end Alembic commands ###
