"""change some properties from str to int & float in tracks table

Revision ID: d4661c4e5953
Revises: 8f526669af0e
Create Date: 2025-06-12 04:53:46.705374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4661c4e5953'
down_revision: Union[str, None] = '8f526669af0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE tracks ALTER COLUMN from_lat TYPE double precision USING from_lat::double precision')
    op.execute('ALTER TABLE tracks ALTER COLUMN from_lng TYPE double precision USING from_lng::double precision')
    op.execute('ALTER TABLE tracks ALTER COLUMN to_lat TYPE double precision USING to_lat::double precision')
    op.execute('ALTER TABLE tracks ALTER COLUMN to_lng TYPE double precision USING to_lng::double precision')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE tracks ALTER COLUMN from_lat TYPE VARCHAR USING from_lat::VARCHAR')
    op.execute('ALTER TABLE tracks ALTER COLUMN from_lng TYPE VARCHAR USING from_lng::VARCHAR')
    op.execute('ALTER TABLE tracks ALTER COLUMN to_lat TYPE VARCHAR USING to_lat::VARCHAR')
    op.execute('ALTER TABLE tracks ALTER COLUMN to_lng TYPE VARCHAR USING to_lng::VARCHAR')
    # ### end Alembic commands ###
