"""add track_user UniqueConstraint to leaderboard table

Revision ID: d534164f559a
Revises: 67a2e11555fe
Create Date: 2025-09-23 00:33:20.225737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd534164f559a'
down_revision: Union[str, None] = '67a2e11555fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_bike_track_gender_rank', 'bike_leaderboard', type_='unique')
    op.create_unique_constraint('uq_bike_leaderboard_track_user', 'bike_leaderboard', ['track_id', 'user_id'])
    op.drop_constraint('uq_running_track_gender_rank', 'running_leaderboard', type_='unique')
    op.create_unique_constraint('uq_running_leaderboard_track_user', 'running_leaderboard', ['track_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_running_leaderboard_track_user', 'running_leaderboard', type_='unique')
    op.create_unique_constraint('uq_running_track_gender_rank', 'running_leaderboard', ['track_id', 'gender', 'rank_position'])
    op.drop_constraint('uq_bike_leaderboard_track_user', 'bike_leaderboard', type_='unique')
    op.create_unique_constraint('uq_bike_track_gender_rank', 'bike_leaderboard', ['track_id', 'gender', 'rank_position'])
    # ### end Alembic commands ###
