"""add card_def_id to table equip_card_transactions

Revision ID: d57e5a8144b6
Revises: 772c48eb3749
Create Date: 2025-09-13 07:11:06.367509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'd57e5a8144b6'
down_revision: Union[str, None] = '772c48eb3749'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equip_card_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('card_def_id', sa.UUID(), nullable=False),
    sa.Column('operation', postgresql.ENUM('RECHARGE', 'CONSUME', 'TRANSFER', 'REWARD', 'WITHDRAW', 'REFUND', 'DESTROY', 'UPGRADE', name='assetoperation', create_type=False), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('equip_card_transactions')
    # ### end Alembic commands ###
