"""add single & team register_card_id in biketrack table

Revision ID: e0e1dbe7dbbb
Revises: 11f7da61232f
Create Date: 2025-12-13 04:08:46.931629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0e1dbe7dbbb'
down_revision: Union[str, None] = '11f7da61232f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bike_tracks', sa.Column('single_register_card_id', sa.UUID(), nullable=True))
    op.execute("UPDATE bike_tracks SET single_register_card_id = '8e1fb157-bf4b-44ca-bdfc-8517603c90ff' WHERE single_register_card_id IS NULL")
    op.alter_column('bike_tracks', 'single_register_card_id', nullable=False)

    op.add_column('bike_tracks', sa.Column('team_register_card_id', sa.UUID(), nullable=True))
    op.execute("UPDATE bike_tracks SET team_register_card_id = '7d36051e-5c98-4d32-9cfb-7c6741f0aac4' WHERE team_register_card_id IS NULL")
    op.alter_column('bike_tracks', 'team_register_card_id', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bike_tracks', 'team_register_card_id')
    op.drop_column('bike_tracks', 'single_register_card_id')
    # ### end Alembic commands ###
