"""separate card_bonus table

Revision ID: e763b25763f8
Revises: f118c9ab37bf
Create Date: 2025-08-26 01:15:50.602699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e763b25763f8'
down_revision: Union[str, None] = 'f118c9ab37bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_bonus_in_bike_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('bonus_time', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('card_bonus_in_running_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('bonus_time', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_running_race_records_history_record_id', table_name='running_race_records_history')
    op.drop_table('running_race_records_history')
    op.drop_index('ix_bike_race_records_history_record_id', table_name='bike_race_records_history')
    op.drop_table('bike_race_records_history')
    op.drop_index('ix_bike_race_path_history_path_id', table_name='bike_race_path_history')
    op.drop_table('bike_race_path_history')
    op.drop_index('ix_running_race_paths_history_path_id', table_name='running_race_paths_history')
    op.drop_table('running_race_paths_history')
    op.drop_table('card_bonus_in_records_history')
    op.drop_table('card_bonus_in_records')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_bonus_in_records',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('record_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('card_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('bonus_time', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='card_bonus_in_records_pkey')
    )
    op.create_table('card_bonus_in_records_history',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('record_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('card_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('bonus_time', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='card_bonus_in_records_history_pkey')
    )
    op.create_table('running_race_paths_history',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('path_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('record_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('path', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='running_race_paths_history_pkey')
    )
    op.create_index('ix_running_race_paths_history_path_id', 'running_race_paths_history', ['path_id'], unique=True)
    op.create_table('bike_race_path_history',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('path_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('record_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('path', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='bike_race_path_history_pkey')
    )
    op.create_index('ix_bike_race_path_history_path_id', 'bike_race_path_history', ['path_id'], unique=True)
    op.create_table('bike_race_records_history',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('record_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('track_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('start_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('duration_seconds', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('path_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='bike_race_records_history_pkey')
    )
    op.create_index('ix_bike_race_records_history_record_id', 'bike_race_records_history', ['record_id'], unique=True)
    op.create_table('running_race_records_history',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('record_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('track_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('start_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('duration_seconds', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('path_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='running_race_records_history_pkey')
    )
    op.create_index('ix_running_race_records_history_record_id', 'running_race_records_history', ['record_id'], unique=True)
    op.drop_table('card_bonus_in_running_records')
    op.drop_table('card_bonus_in_bike_records')
    # ### end Alembic commands ###
