"""seperate seasons table & add asset/team table

Revision ID: e9cabe1c04f0
Revises: 532e4b63f6a5
Create Date: 2025-06-30 00:52:40.684390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e9cabe1c04f0'
down_revision: Union[str, None] = '532e4b63f6a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bike_seasons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('season_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bike_seasons_season_id'), 'bike_seasons', ['season_id'], unique=True)
    op.create_table('cp_asset_defs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('prop_type', sa.Enum('registration_card', 'team_card', name='cpassettype'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cp_asset_defs_asset_id'), 'cp_asset_defs', ['asset_id'], unique=True)
    op.create_table('equipment_card_defs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('equip_id', sa.String(), nullable=False),
    sa.Column('validation_token', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('WATER', 'FIRE', name='equipmentcardtype'), nullable=False),
    sa.Column('rarity', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('basic_config', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_card_defs_equip_id'), 'equipment_card_defs', ['equip_id'], unique=True)
    op.create_table('running_seasons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('season_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_running_seasons_season_id'), 'running_seasons', ['season_id'], unique=True)
    op.create_table('ccasset_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('asset_type', sa.Enum('COIN', 'COUPON', 'VOUCHER', name='ccassettype'), nullable=False),
    sa.Column('operation', sa.Enum('RECHARGE', 'CONSUME', 'TRANSFER', 'REWARD', 'WITHDRAW', 'REFUND', name='assetoperation'), nullable=False),
    sa.Column('change_amount', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cp_registration_card_defs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sport_type', sa.Enum('running', 'bike', name='sporttype'), nullable=False),
    sa.Column('is_team', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['cp_asset_defs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cp_team_card_defs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sport_type', sa.Enum('running', 'bike', name='sporttype'), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['cp_asset_defs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cpasset_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('prop_def_id', sa.UUID(), nullable=False),
    sa.Column('operation', sa.Enum('RECHARGE', 'CONSUME', 'TRANSFER', 'REWARD', 'WITHDRAW', 'REFUND', name='assetoperation'), nullable=False),
    sa.Column('change_amount', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['prop_def_id'], ['cp_asset_defs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_ccassets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('asset_type', sa.Enum('COIN', 'COUPON', 'VOUCHER', name='ccassettype', create_type=False), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=True),
    sa.Column('can_recharge', sa.Boolean(), nullable=True),
    sa.Column('can_withdraw', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'asset_type', name='uix_user_ccasset')
    )
    op.create_table('user_cpassets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('prop_def_id', sa.UUID(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['prop_def_id'], ['cp_asset_defs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'prop_def_id', name='uix_user_cpasset')
    )
    op.create_table('user_equipment_cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('equipment_def_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('lucky_value', sa.Float(), nullable=True),
    sa.Column('income_multiple', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['equipment_def_id'], ['equipment_card_defs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bike_teams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('team_code', sa.String(), nullable=False),
    sa.Column('track_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('members_count_max', sa.Integer(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('start_date_real', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['bike_tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bike_teams_team_code'), 'bike_teams', ['team_code'], unique=True)
    op.create_index(op.f('ix_bike_teams_team_id'), 'bike_teams', ['team_id'], unique=True)
    op.create_table('running_race_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('record_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('track_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('notStarted', 'recording', 'completed', name='recordstatus'), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('is_team', sa.Boolean(), nullable=True),
    sa.Column('team_code', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['running_tracks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_running_race_records_record_id'), 'running_race_records', ['record_id'], unique=True)
    op.create_table('bike_team_applied_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.String(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('introduction', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['bike_teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bike_team_applied_members_member_id'), 'bike_team_applied_members', ['member_id'], unique=True)
    op.create_table('bike_team_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.String(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('is_leader', sa.Boolean(), nullable=True),
    sa.Column('is_registered', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['bike_teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bike_team_members_member_id'), 'bike_team_members', ['member_id'], unique=True)

    op.execute("""
        INSERT INTO bike_seasons (id, season_id, name, start_date, end_date, image_url, created_at)
        SELECT id, season_id, name, start_date, end_date, image_url, created_at
        FROM seasons
        WHERE sport_type = 'bike'
    """)
    op.execute("""
        INSERT INTO running_seasons (id, season_id, name, start_date, end_date, image_url, created_at)
        SELECT id, season_id, name, start_date, end_date, image_url, created_at
        FROM seasons
        WHERE sport_type = 'running'
    """)
    op.drop_constraint('bike_events_season_id_fkey', 'bike_events', type_='foreignkey')
    op.drop_constraint('running_events_season_id_fkey', 'running_events', type_='foreignkey')
    op.drop_index('ix_seasons_season_id', table_name='seasons')
    op.drop_table('seasons')
    op.create_foreign_key(None, 'bike_events', 'bike_seasons', ['season_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'running_events', 'running_seasons', ['season_id'], ['id'], ondelete='CASCADE')

    op.add_column('bike_race_records', sa.Column('record_id', sa.String(), nullable=False))
    op.alter_column('bike_race_records', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('notStarted', 'recording', 'completed', name='recordstatus'),
               existing_nullable=True, postgresql_using="status::recordstatus")
    op.create_index(op.f('ix_bike_race_records_record_id'), 'bike_race_records', ['record_id'], unique=True)
    op.drop_column('bike_race_records', 'score')
    op.drop_column('bike_tracks', 'fee')
    op.drop_column('running_tracks', 'fee')
    
    gender_enum = postgresql.ENUM('male', 'female', name='gender')
    gender_enum.create(op.get_bind(), checkfirst=True)
    op.alter_column('users', 'gender',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('male', 'female', name='gender'),
               existing_nullable=True, postgresql_using="gender::gender")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'gender',
               existing_type=sa.Enum('male', 'female', name='gender'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.add_column('running_tracks', sa.Column('fee', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'running_events', type_='foreignkey')
    op.create_foreign_key('running_events_season_id_fkey', 'running_events', 'seasons', ['season_id'], ['id'], ondelete='CASCADE')
    op.add_column('bike_tracks', sa.Column('fee', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('bike_race_records', sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_bike_race_records_record_id'), table_name='bike_race_records')
    op.alter_column('bike_race_records', 'status',
               existing_type=sa.Enum('notStarted', 'recording', 'completed', name='recordstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('bike_race_records', 'record_id')
    op.drop_constraint(None, 'bike_events', type_='foreignkey')
    op.create_foreign_key('bike_events_season_id_fkey', 'bike_events', 'seasons', ['season_id'], ['id'], ondelete='CASCADE')
    op.create_table('seasons',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('start_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('end_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('sport_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('season_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='seasons_pkey')
    )
    op.create_index('ix_seasons_season_id', 'seasons', ['season_id'], unique=True)
    op.drop_index(op.f('ix_bike_team_members_member_id'), table_name='bike_team_members')
    op.drop_table('bike_team_members')
    op.drop_index(op.f('ix_bike_team_applied_members_member_id'), table_name='bike_team_applied_members')
    op.drop_table('bike_team_applied_members')
    op.drop_index(op.f('ix_running_race_records_record_id'), table_name='running_race_records')
    op.drop_table('running_race_records')
    op.drop_index(op.f('ix_bike_teams_team_id'), table_name='bike_teams')
    op.drop_index(op.f('ix_bike_teams_team_code'), table_name='bike_teams')
    op.drop_table('bike_teams')
    op.drop_table('user_equipment_cards')
    op.drop_table('user_cpassets')
    op.drop_table('user_ccassets')
    op.drop_table('cpasset_transactions')
    op.drop_table('cp_team_card_defs')
    op.drop_table('cp_registration_card_defs')
    op.drop_table('ccasset_transactions')
    op.drop_index(op.f('ix_running_seasons_season_id'), table_name='running_seasons')
    op.drop_table('running_seasons')
    op.drop_index(op.f('ix_equipment_card_defs_equip_id'), table_name='equipment_card_defs')
    op.drop_table('equipment_card_defs')
    op.drop_index(op.f('ix_cp_asset_defs_asset_id'), table_name='cp_asset_defs')
    op.drop_table('cp_asset_defs')
    op.drop_index(op.f('ix_bike_seasons_season_id'), table_name='bike_seasons')
    op.drop_table('bike_seasons')
    # ### end Alembic commands ###
