"""optimize_buff_grids_table

Revision ID: ee2273c09478
Revises: acb543ae65eb
Create Date: 2026-05-13 23:21:39.438395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'ee2273c09478'
down_revision: Union[str, None] = 'acb543ae65eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bikegridconditiontype = sa.Enum(
        'distance', 'speed', 'none',
       name='bikegridconditiontype'
    )
    bikegridconditiontype.create(op.get_bind(), checkfirst=True)

    runninggridconditiontype = sa.Enum(
        'distance', 'speed', 'none',
       name='runninggridconditiontype'
    )
    runninggridconditiontype.create(op.get_bind(), checkfirst=True)

    op.alter_column(
        'bike_effect_grids',
        'condition_type',
        existing_type=sa.VARCHAR(),
        type_=postgresql.ENUM(
            'distance', 'speed', 'none',
            name='bikegridconditiontype',
            create_type=False
        ),
        existing_nullable=False,
        postgresql_using='condition_type::bikegridconditiontype'
    )
    op.alter_column(
        'running_effect_grids',
        'condition_type',
        existing_type=sa.VARCHAR(),
        type_=postgresql.ENUM(
            'distance', 'speed', 'none',
            name='runninggridconditiontype',
            create_type=False
        ),
        existing_nullable=False,
        postgresql_using='condition_type::runninggridconditiontype'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
