"""change birth_date to Date type in user_realname_identities table

Revision ID: ee6a7cd5d2eb
Revises: b4e457342c8d
Create Date: 2026-03-18 07:00:55.071032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee6a7cd5d2eb'
down_revision: Union[str, None] = 'b4e457342c8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_realname_identities', sa.Column('birth_date_new', sa.Date(), nullable=True))
    
    op.execute("""
        UPDATE user_realname_identities
        SET birth_date_new = TO_DATE(birth_date, 'DD-MM-YYYY')
    """)

    op.drop_column('user_realname_identities', 'birth_date')

    op.alter_column('user_realname_identities', 'birth_date_new', new_column_name='birth_date')

    op.alter_column('user_realname_identities', 'birth_date', nullable=False)


    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
