"""add created_at & image_url to tables

Revision ID: ef36cc82d9d3
Revises: 932cbfc2b831
Create Date: 2025-06-05 04:14:18.621642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef36cc82d9d3'
down_revision: Union[str, None] = '932cbfc2b831'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('image_url', sa.String(), nullable=False))
    op.add_column('events', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))

    op.add_column('regions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))

    op.add_column('seasons', sa.Column('image_url', sa.String(), nullable=True))
    op.execute("UPDATE seasons SET image_url = '/resources/placeholder/season.png'")
    op.alter_column('seasons', 'image_url', nullable=False)
    op.add_column('seasons', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))

    op.add_column('tracks', sa.Column('image_url', sa.String(), nullable=False))
    op.add_column('tracks', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))

    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_unique_constraint(None, 'users', ['nickname'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'created_at')
    op.drop_column('tracks', 'created_at')
    op.drop_column('tracks', 'image_url')
    op.drop_column('seasons', 'created_at')
    op.drop_column('seasons', 'image_url')
    op.drop_column('regions', 'created_at')
    op.drop_column('events', 'created_at')
    op.drop_column('events', 'image_url')
    # ### end Alembic commands ###
