"""add radius & terrain_type to track table

Revision ID: ef4279d7e35a
Revises: fb5936acbfd0
Create Date: 2025-10-28 03:53:29.170824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'ef4279d7e35a'
down_revision: Union[str, None] = 'fb5936acbfd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bike_terrain_type_enum = postgresql.ENUM('road', 'crossCountry', 'enduro', 'downHill', 'other', name='biketrackterraintype')
    bike_terrain_type_enum.create(op.get_bind(), checkfirst=True)
    running_terrain_type_enum = postgresql.ENUM('road', 'mountain', name='runningtrackterraintype')
    running_terrain_type_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('bike_tracks', sa.Column('from_radius', sa.Integer(), nullable=True))
    op.execute("UPDATE bike_tracks SET from_radius = 10 WHERE from_radius IS NULL")
    op.alter_column('bike_tracks', 'from_radius', nullable=False)

    op.add_column('bike_tracks', sa.Column('to_radius', sa.Integer(), nullable=True))
    op.execute("UPDATE bike_tracks SET to_radius = 10 WHERE to_radius IS NULL")
    op.alter_column('bike_tracks', 'to_radius', nullable=False)

    op.add_column('bike_tracks', sa.Column('terrain_type', postgresql.ENUM('road', 'crossCountry', 'enduro', 'downHill', 'other', name='biketrackterraintype', create_type=False), nullable=True))
    op.execute("UPDATE bike_tracks SET terrain_type = 'road' WHERE terrain_type IS NULL")
    op.alter_column('bike_tracks', 'terrain_type', nullable=False)

    op.add_column('running_tracks', sa.Column('from_radius', sa.Integer(), nullable=True))
    op.execute("UPDATE running_tracks SET from_radius = 10 WHERE from_radius IS NULL")
    op.alter_column('running_tracks', 'from_radius', nullable=False)

    op.add_column('running_tracks', sa.Column('to_radius', sa.Integer(), nullable=True))
    op.execute("UPDATE running_tracks SET to_radius = 10 WHERE to_radius IS NULL")
    op.alter_column('running_tracks', 'to_radius', nullable=False)

    op.add_column('running_tracks', sa.Column('terrain_type', postgresql.ENUM('road', 'mountain', name='runningtrackterraintype', create_type=False), nullable=True))
    op.execute("UPDATE running_tracks SET terrain_type = 'road' WHERE terrain_type IS NULL")
    op.alter_column('running_tracks', 'terrain_type', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('running_tracks', 'terrain_type')
    op.drop_column('running_tracks', 'to_radius')
    op.drop_column('running_tracks', 'from_radius')
    op.drop_column('bike_tracks', 'terrain_type')
    op.drop_column('bike_tracks', 'to_radius')
    op.drop_column('bike_tracks', 'from_radius')
    # ### end Alembic commands ###
