"""enable cascade deletes in regions/seasons/events/tracks table

Revision ID: ef4f785b1192
Revises: d4661c4e5953
Create Date: 2025-06-14 04:27:45.975241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef4f785b1192'
down_revision: Union[str, None] = 'd4661c4e5953'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('events_season_id_fkey', 'events', type_='foreignkey')
    op.drop_constraint('events_region_id_fkey', 'events', type_='foreignkey')
    op.create_foreign_key(None, 'events', 'regions', ['region_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'events', 'seasons', ['season_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('tracks_event_id_fkey', 'tracks', type_='foreignkey')
    op.create_foreign_key(None, 'tracks', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tracks', type_='foreignkey')
    op.create_foreign_key('tracks_event_id_fkey', 'tracks', 'events', ['event_id'], ['id'])
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.create_foreign_key('events_region_id_fkey', 'events', 'regions', ['region_id'], ['id'])
    op.create_foreign_key('events_season_id_fkey', 'events', 'seasons', ['season_id'], ['id'])
    # ### end Alembic commands ###
