"""add path & card_bonus table, optimize equipcard table

Revision ID: f118c9ab37bf
Revises: 2f9ed4b067fc
Create Date: 2025-08-25 22:35:43.092314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f118c9ab37bf'
down_revision: Union[str, None] = '2f9ed4b067fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bike_race_path_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('path_id', sa.String(), nullable=False),
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('path', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bike_race_path_history_path_id'), 'bike_race_path_history', ['path_id'], unique=True)
    op.create_table('bike_race_paths',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('path_id', sa.String(), nullable=False),
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('path', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bike_race_paths_path_id'), 'bike_race_paths', ['path_id'], unique=True)
    op.create_table('card_bonus_in_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('bonus_time', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('card_bonus_in_records_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('bonus_time', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('running_race_paths',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('path_id', sa.String(), nullable=False),
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('path', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_running_race_paths_path_id'), 'running_race_paths', ['path_id'], unique=True)
    op.create_table('running_race_paths_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('path_id', sa.String(), nullable=False),
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('path', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_running_race_paths_history_path_id'), 'running_race_paths_history', ['path_id'], unique=True)
    op.drop_table('running_team_members_history')
    op.drop_table('bike_team_members_history')
    op.add_column('bike_race_records', sa.Column('path_id', sa.UUID(), nullable=True))
    op.add_column('bike_race_records_history', sa.Column('path_id', sa.UUID(), nullable=True))
    op.add_column('equipment_card_defs', sa.Column('def_id', sa.String(), nullable=False))
    op.add_column('equipment_card_defs', sa.Column('name', sa.String(), nullable=False))
    op.add_column('equipment_card_defs', sa.Column('sport_type', sa.Enum('running', 'bike', name='sporttype'), nullable=False))
    op.add_column('equipment_card_defs', sa.Column('skill1_description', sa.String(), nullable=True))
    op.add_column('equipment_card_defs', sa.Column('skill2_description', sa.String(), nullable=True))
    op.add_column('equipment_card_defs', sa.Column('skill3_description', sa.String(), nullable=True))
    op.add_column('equipment_card_defs', sa.Column('version', sa.String(), nullable=False))
    op.add_column('equipment_card_defs', sa.Column('type_name', sa.String(), nullable=False))
    op.add_column('equipment_card_defs', sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('equipment_card_defs', sa.Column('effect_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.drop_index('ix_equipment_card_defs_equip_id', table_name='equipment_card_defs')
    op.create_index(op.f('ix_equipment_card_defs_def_id'), 'equipment_card_defs', ['def_id'], unique=True)
    op.drop_column('equipment_card_defs', 'equip_id')
    op.drop_column('equipment_card_defs', 'basic_config')
    op.drop_column('equipment_card_defs', 'type')
    op.add_column('running_race_records', sa.Column('path_id', sa.UUID(), nullable=True))
    op.add_column('running_race_records_history', sa.Column('path_id', sa.UUID(), nullable=True))
    op.add_column('user_equipment_cards', sa.Column('card_id', sa.String(), nullable=False))
    op.add_column('user_equipment_cards', sa.Column('skill1_level', sa.Integer(), nullable=True))
    op.add_column('user_equipment_cards', sa.Column('skill2_level', sa.Integer(), nullable=True))
    op.add_column('user_equipment_cards', sa.Column('skill3_level', sa.Integer(), nullable=True))
    op.add_column('user_equipment_cards', sa.Column('effect_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.create_index(op.f('ix_user_equipment_cards_card_id'), 'user_equipment_cards', ['card_id'], unique=True)
    op.drop_column('user_equipment_cards', 'income_multiple')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_equipment_cards', sa.Column('income_multiple', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_user_equipment_cards_card_id'), table_name='user_equipment_cards')
    op.drop_column('user_equipment_cards', 'effect_config')
    op.drop_column('user_equipment_cards', 'skill3_level')
    op.drop_column('user_equipment_cards', 'skill2_level')
    op.drop_column('user_equipment_cards', 'skill1_level')
    op.drop_column('user_equipment_cards', 'card_id')
    op.drop_column('running_race_records_history', 'path_id')
    op.drop_column('running_race_records', 'path_id')
    op.add_column('equipment_card_defs', sa.Column('type', postgresql.ENUM('WATER', 'FIRE', name='equipmentcardtype'), autoincrement=False, nullable=False))
    op.add_column('equipment_card_defs', sa.Column('basic_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('equipment_card_defs', sa.Column('equip_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_equipment_card_defs_def_id'), table_name='equipment_card_defs')
    op.create_index('ix_equipment_card_defs_equip_id', 'equipment_card_defs', ['equip_id'], unique=True)
    op.drop_column('equipment_card_defs', 'effect_config')
    op.drop_column('equipment_card_defs', 'tags')
    op.drop_column('equipment_card_defs', 'type_name')
    op.drop_column('equipment_card_defs', 'version')
    op.drop_column('equipment_card_defs', 'skill3_description')
    op.drop_column('equipment_card_defs', 'skill2_description')
    op.drop_column('equipment_card_defs', 'skill1_description')
    op.drop_column('equipment_card_defs', 'sport_type')
    op.drop_column('equipment_card_defs', 'name')
    op.drop_column('equipment_card_defs', 'def_id')
    op.drop_column('bike_race_records_history', 'path_id')
    op.drop_column('bike_race_records', 'path_id')
    op.create_table('bike_team_members_history',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('is_leader', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='bike_team_members_history_pkey')
    )
    op.create_table('running_team_members_history',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('is_leader', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='running_team_members_history_pkey')
    )
    op.drop_index(op.f('ix_running_race_paths_history_path_id'), table_name='running_race_paths_history')
    op.drop_table('running_race_paths_history')
    op.drop_index(op.f('ix_running_race_paths_path_id'), table_name='running_race_paths')
    op.drop_table('running_race_paths')
    op.drop_table('card_bonus_in_records_history')
    op.drop_table('card_bonus_in_records')
    op.drop_index(op.f('ix_bike_race_paths_path_id'), table_name='bike_race_paths')
    op.drop_table('bike_race_paths')
    op.drop_index(op.f('ix_bike_race_path_history_path_id'), table_name='bike_race_path_history')
    op.drop_table('bike_race_path_history')
    # ### end Alembic commands ###
