"""add_training_route_tables

Revision ID: f131e4059432
Revises: 8ebeaadbfd63
Create Date: 2026-04-26 15:48:53.423986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = 'f131e4059432'
down_revision: Union[str, None] = '8ebeaadbfd63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bike_training_routes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('route_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('region_id', sa.UUID(), nullable=False),
    sa.Column('route_type', sa.Enum('pointToPoint', 'multiPoints', name='routetype'), nullable=False),
    sa.Column('route_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('route_geometry', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('start_point', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('end_point', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('elevation_difference', sa.Integer(), nullable=False),
    sa.Column('total_distance', sa.Float(), nullable=False),
    sa.Column('terrain_type', postgresql.ENUM('road', 'crossCountry', 'enduro', 'downHill', 'other', name='biketrackterraintype', create_type=False), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('enable_ranklist', sa.Boolean(), nullable=False),
    sa.Column('enable_magiccard', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bike_routes_end_point', 'bike_training_routes', ['end_point'], unique=False, postgresql_using='gist')
    op.create_index('idx_bike_routes_geometry', 'bike_training_routes', ['route_geometry'], unique=False, postgresql_using='gist')
    op.create_index('idx_bike_routes_start_point', 'bike_training_routes', ['start_point'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_bike_training_routes_region_id'), 'bike_training_routes', ['region_id'], unique=False)
    op.create_index(op.f('ix_bike_training_routes_route_id'), 'bike_training_routes', ['route_id'], unique=True)
    op.create_index(op.f('ix_bike_training_routes_user_id'), 'bike_training_routes', ['user_id'], unique=False)

    op.create_table('running_training_routes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('route_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('region_id', sa.UUID(), nullable=False),
    sa.Column('route_type', sa.Enum('pointToPoint', 'multiPoints', name='routetype'), nullable=False),
    sa.Column('route_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('route_geometry', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('start_point', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('end_point', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('elevation_difference', sa.Integer(), nullable=False),
    sa.Column('total_distance', sa.Float(), nullable=False),
    sa.Column('terrain_type', postgresql.ENUM('road', 'mountain', name='runningtrackterraintype', create_type=False), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('enable_ranklist', sa.Boolean(), nullable=False),
    sa.Column('enable_magiccard', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_running_routes_end_point', 'running_training_routes', ['end_point'], unique=False, postgresql_using='gist')
    op.create_index('idx_running_routes_geometry', 'running_training_routes', ['route_geometry'], unique=False, postgresql_using='gist')
    op.create_index('idx_running_routes_start_point', 'running_training_routes', ['start_point'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_running_training_routes_region_id'), 'running_training_routes', ['region_id'], unique=False)
    op.create_index(op.f('ix_running_training_routes_route_id'), 'running_training_routes', ['route_id'], unique=True)
    op.create_index(op.f('ix_running_training_routes_user_id'), 'running_training_routes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
