"""add single & team register_card_id in runningtrack table

Revision ID: f2a64d0ef351
Revises: e0e1dbe7dbbb
Create Date: 2025-12-13 19:36:24.999058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2a64d0ef351'
down_revision: Union[str, None] = 'e0e1dbe7dbbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('running_tracks', sa.Column('single_register_card_id', sa.UUID(), nullable=True))
    op.execute("UPDATE running_tracks SET single_register_card_id = 'cbfa494d-f9e9-4b95-a067-5ad73ece8148' WHERE single_register_card_id IS NULL")
    op.alter_column('running_tracks', 'single_register_card_id', nullable=False)

    op.add_column('running_tracks', sa.Column('team_register_card_id', sa.UUID(), nullable=True))
    op.execute("UPDATE running_tracks SET team_register_card_id = 'af12347a-6e75-46c3-9f3f-881847008243' WHERE team_register_card_id IS NULL")
    op.alter_column('running_tracks', 'team_register_card_id', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('running_tracks', 'team_register_card_id')
    op.drop_column('running_tracks', 'single_register_card_id')
    # ### end Alembic commands ###
