"""update_to_global_grids_system

Revision ID: f420d9f5ef7b
Revises: 8c976e67ae77
Create Date: 2026-04-04 18:54:22.353802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f420d9f5ef7b'
down_revision: Union[str, None] = '8c976e67ae77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_country_grid_cells_country_code_gridx_gridy'), 'country_grid_cells', type_='unique')
    op.execute('''
    TRUNCATE country_grid_cells CASCADE;
    TRUNCATE region_grid_cells CASCADE;
    TRUNCATE user_grid_familiarity_bike;
    TRUNCATE user_grid_familiarity_running;
    TRUNCATE user_grid_familiarity_bike_agg;
    TRUNCATE user_grid_familiarity_running_agg;
    ''')
    op.create_unique_constraint('uq_country_grid_cells_gridx_gridy', 'country_grid_cells', ['grid_x', 'grid_y'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # skip downgrade
    # ### end Alembic commands ###
