"""add report to feedbackmailtype enum

Revision ID: faadb4921b95
Revises: 0e304109392b
Create Date: 2025-12-11 22:12:27.257442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faadb4921b95'
down_revision: Union[str, None] = '0e304109392b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

enum_name = "feedbackmailtype"  

# 你新增的 enum 值
new_value = "report"

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(f"ALTER TYPE {enum_name} ADD VALUE IF NOT EXISTS '{new_value}';")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
