"""some daily task optimize

Revision ID: fb5936acbfd0
Revises: 38c36d335608
Create Date: 2025-10-24 07:03:24.837704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb5936acbfd0'
down_revision: Union[str, None] = '38c36d335608'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bike_daily_task', 'reward_stage3_id',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using="reward_stage3_id::uuid")
    op.alter_column('running_daily_task', 'reward_stage3_id',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using="reward_stage3_id::uuid")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('running_daily_task', 'reward_stage3_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               postgresql_using="reward_stage3_id::varchar")
    op.alter_column('bike_daily_task', 'reward_stage3_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               postgresql_using="reward_stage3_id::varchar")
    # ### end Alembic commands ###
