name: Deploy Dev

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Docker login to registry (Docker Hub or other)
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/sporreer_backend:dev-latest

    - name: Deploy to Dev Server
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.DEV_SERVER_HOST }}
        username: ${{ secrets.DEV_SERVER_USER }}
        key: ${{ secrets.DEV_SERVER_SSH_KEY }}
        script: |
          cd /opt/sporreer_dev
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/sporreer_backend:dev-latest
          docker compose down
          docker compose up -d --force-recreate
